// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/pty&apos; operation.
/// </summary>
public sealed record PtyListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<Pty>? _ptys;
    private readonly LocationInfo? _location;
    /// <summary>
    /// Initializes a success instance of the &apos;PtyListResponse&apos; envelope.
    /// </summary>
    public PtyListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal PtyListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Ptys = null!;
        Location = null!;
    }

    /// <summary>
    /// Gets the Ptys payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<Pty> Ptys { get => _ptys ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Ptys."); init => _ptys = value; }
    /// <summary>
    /// Gets the location the server resolved for the request; guarded on the error path.
    /// </summary>
    public required LocationInfo Location { get => _location ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Location."); init => _location = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_ptys is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Ptys = ").Append(_ptys);
        return true;
    }
}
