// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// A bound &apos;PtyRawClient&apos; handle; it holds an immutable identifier and the shared pipeline.
/// </summary>
internal sealed class PtyRawClient
{
    private static readonly PtyUpdatePutRequest EmptyPtyUpdatePutRequest = new();
    private readonly Pipeline? _pipeline;
    private readonly string? _ptyId;
    internal PtyRawClient(Pipeline pipeline, string ptyId)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        ArgumentException.ThrowIfNullOrWhiteSpace(ptyId);
        if (ptyId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(ptyId));
        }

        _pipeline = pipeline;
        _ptyId = ptyId;
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("PtyRawClient", "Pipeline");
    private string PtyId => _ptyId ?? throw MockSeam.CreateError("PtyRawClient", "PtyId");

    /// <summary>
    /// Get PTY session. Get one PTY session, including its exit code once exited.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PtyResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    internal Task<PtyResponse> GetPtyAsync(PtyRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Ptys.GetPty(PtyId, request), PtyResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Create PTY WebSocket token. Create a short-lived single-use ticket for opening a PTY WebSocket connection.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "xOpencodeTicket">The &apos;x-opencode-ticket&apos; request header; omitted when null.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PtyConnectTokenPostResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 403, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    internal Task<PtyConnectTokenPostResponse> PostConnectTokenAsync(PtyConnectTokenPostRequest? request = null, string? xOpencodeTicket = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var declaredHeaders = new List<DeclaredHeader>(1);
        if (xOpencodeTicket is not null)
        {
            declaredHeaders.Add(new DeclaredHeader("x-opencode-ticket", xOpencodeTicket));
        }

        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Ptys.PostConnectToken(PtyId, request), PtyConnectTokenPostResponseAdapter.Instance, requestOptions, declaredHeaders: declaredHeaders, cancellationToken);
    }

    /// <summary>
    /// Update PTY session. Update the title or viewport size of one PTY session.
    /// </summary>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PtyUpdatePutResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    internal Task<PtyUpdatePutResponse> PutUpdateAsync(PtyUpdatePutRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Put, OpenCodeRoutes.Ptys.PutUpdate(PtyId, request), request ?? EmptyPtyUpdatePutRequest, OpenCodeJsonContext.Default.PtyUpdatePutRequest, PtyUpdatePutResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Remove PTY session. Terminate and remove one PTY session.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PtyRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    internal Task<PtyRemoveResponse> RemovePtyAsync(PtyRemoveRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Ptys.RemovePty(PtyId, request), PtyRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
