// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;GET /api/shell/{id}/output&apos; query.
/// </summary>
public sealed record ShellOutputRequest
{
    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    public LocationSelector? Location { get; init; }
    /// <summary>
    /// Gets the &apos;cursor&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Cursor { get; init; }
    /// <summary>
    /// Gets the &apos;limit&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Limit { get; init; }
}
