// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/reference&apos; operation.
/// </summary>
public sealed record ReferenceListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<ReferenceInfo>? _references;
    private readonly LocationInfo? _location;
    /// <summary>
    /// Initializes a success instance of the &apos;ReferenceListResponse&apos; envelope.
    /// </summary>
    public ReferenceListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal ReferenceListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        References = null!;
        Location = null!;
    }

    /// <summary>
    /// Gets the References payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<ReferenceInfo> References { get => _references ?? throw new InvalidOperationException("The response is an error; check IsError before accessing References."); init => _references = value; }
    /// <summary>
    /// Gets the location the server resolved for the request; guarded on the error path.
    /// </summary>
    public required LocationInfo Location { get => _location ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Location."); init => _location = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_references is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("References = ").Append(_references);
        return true;
    }
}
