// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/project&apos; operation.
/// </summary>
public sealed record ProjectListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<Project>? _projects;
    /// <summary>
    /// Initializes a success instance of the &apos;ProjectListResponse&apos; envelope.
    /// </summary>
    public ProjectListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal ProjectListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Projects = null!;
    }

    /// <summary>
    /// Gets the Projects payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<Project> Projects { get => _projects ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Projects."); init => _projects = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_projects is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Projects = ").Append(_projects);
        return true;
    }
}
