<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testably.Abstractions.Testing" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Spectre.Console.Cli.Testing" />
    <PackageReference Include="Verify.TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../tools/OpenCode.Sdk.Tools/OpenCode.Sdk.Tools.csproj" />
  </ItemGroup>

</Project>
