// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/generate&apos; responses onto &apos;GenerateTextPostResponse&apos;.
/// </summary>
internal sealed class GenerateTextPostResponseAdapter : ResponseAdapter<GenerateTextPostResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private GenerateTextPostResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static GenerateTextPostResponseAdapter Instance { get; } = new GenerateTextPostResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override GenerateTextPostResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Text = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.GenerateTextPostResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override GenerateTextPostResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new GenerateTextPostResponse
            {
                Status = status,
                Text = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.GenerateTextPostResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new GenerateTextPostResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new GenerateTextPostResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            503 => new GenerateTextPostResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new GenerateTextPostResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
