// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/integration/{integrationID}/connect/command&apos; responses onto &apos;IntegrationCommandConnectPostResponse&apos;.
/// </summary>
internal sealed class IntegrationCommandConnectPostResponseAdapter : ResponseAdapter<IntegrationCommandConnectPostResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private IntegrationCommandConnectPostResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static IntegrationCommandConnectPostResponseAdapter Instance { get; } = new IntegrationCommandConnectPostResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override IntegrationCommandConnectPostResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.IntegrationCommandConnectPostResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override IntegrationCommandConnectPostResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.IntegrationCommandConnectPostResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new IntegrationCommandConnectPostResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new IntegrationCommandConnectPostResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            _ => new IntegrationCommandConnectPostResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static IntegrationCommandConnectPostResponse CreateSuccess(int status, IntegrationCommandConnectPostResponseEnvelope envelope) => new()
    {
        Status = status,
        CommandConnect = envelope.Data,
        Location = envelope.Location
    };
}
