// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;PUT /api/experimental/persistent-pty/{ptyID}&apos; responses onto &apos;PersistentPtyUpdatePutResponse&apos;.
/// </summary>
internal sealed class PersistentPtyUpdatePutResponseAdapter : ResponseAdapter<PersistentPtyUpdatePutResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["PtyNotFoundError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private PersistentPtyUpdatePutResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static PersistentPtyUpdatePutResponseAdapter Instance { get; } = new PersistentPtyUpdatePutResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override PersistentPtyUpdatePutResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Update = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.PersistentPtyUpdatePutResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override PersistentPtyUpdatePutResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new PersistentPtyUpdatePutResponse
            {
                Status = status,
                Update = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.PersistentPtyUpdatePutResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new PersistentPtyUpdatePutResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new PersistentPtyUpdatePutResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new PersistentPtyUpdatePutResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            503 => new PersistentPtyUpdatePutResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new PersistentPtyUpdatePutResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
