// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/session/{sessionID}/rename&apos; responses onto &apos;SessionRenameResponse&apos;.
/// </summary>
internal sealed class SessionRenameResponseAdapter : ResponseAdapter<SessionRenameResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["SessionNotFoundError"];
    private SessionRenameResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionRenameResponseAdapter Instance { get; } = new SessionRenameResponseAdapter();
    /// <summary>
    /// Gets the declared success status.
    /// </summary>
    public override int SuccessStatusCode => 204;
    /// <summary>
    /// Gets whether this success carries a JSON body.
    /// </summary>
    public override bool ReadsSuccessBody => false;

    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionRenameResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionRenameResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new SessionRenameResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw UndeclaredSuccessFailure(status),
            400 => new SessionRenameResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionRenameResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionRenameResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new SessionRenameResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
