// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/session/{sessionID}/generate&apos; responses onto &apos;SessionGeneratePostResponse&apos;.
/// </summary>
internal sealed class SessionGeneratePostResponseAdapter : ResponseAdapter<SessionGeneratePostResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["SessionNotFoundError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private SessionGeneratePostResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionGeneratePostResponseAdapter Instance { get; } = new SessionGeneratePostResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionGeneratePostResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Generate = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.SessionGeneratePostResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionGeneratePostResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new SessionGeneratePostResponse
            {
                Status = status,
                Generate = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionGeneratePostResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionGeneratePostResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionGeneratePostResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionGeneratePostResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            503 => new SessionGeneratePostResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new SessionGeneratePostResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
