// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/session/{sessionID}&apos; responses onto &apos;SessionResponse&apos;.
/// </summary>
internal sealed class SessionResponseAdapter : ResponseAdapter<SessionResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["SessionNotFoundError"];
    private SessionResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionResponseAdapter Instance { get; } = new SessionResponseAdapter();

    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new SessionResponse
            {
                Status = status,
                Session = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionResponseEnvelope).Data
            },
            >= 200 and < 300 => throw UndeclaredSuccessFailure(status),
            400 => new SessionResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new SessionResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
