// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/session/{sessionID}/command&apos; responses onto &apos;SessionCommandPostResponse&apos;.
/// </summary>
internal sealed class SessionCommandPostResponseAdapter : ResponseAdapter<SessionCommandPostResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["CommandNotFoundError", "SessionNotFoundError"];
    private static readonly string[] Status500Tags = ["CommandExecutionError"];
    private SessionCommandPostResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionCommandPostResponseAdapter Instance { get; } = new SessionCommandPostResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        204 => StatusVerdict.NoContentSuccess,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        500 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionCommandPostResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionCommandPostResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new SessionCommandPostResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionCommandPostResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionCommandPostResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionCommandPostResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            500 => new SessionCommandPostResponse(status, ReadTolerantError(rawBody, Status500Tags), rawBody),
            _ => new SessionCommandPostResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
