// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/session&apos; responses onto &apos;SessionListResponse&apos;.
/// </summary>
internal sealed class SessionListResponseAdapter : ResponseAdapter<SessionListResponse>
{
    private static readonly string[] Status400Tags = ["InvalidCursorError", "InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private SessionListResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionListResponseAdapter Instance { get; } = new SessionListResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionListResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.SessionListResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionListResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionListResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionListResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionListResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            _ => new SessionListResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static SessionListResponse CreateSuccess(int status, SessionListResponseEnvelope envelope) => new()
    {
        Status = status,
        Sessions = envelope.Data,
        Cursor = envelope.Cursor
    };
}
