// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/shell&apos; responses onto &apos;ShellCreateResponse&apos;.
/// </summary>
internal sealed class ShellCreateResponseAdapter : ResponseAdapter<ShellCreateResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private ShellCreateResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ShellCreateResponseAdapter Instance { get; } = new ShellCreateResponseAdapter();

    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ShellCreateResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.ShellCreateResponseEnvelope)),
            >= 200 and < 300 => throw UndeclaredSuccessFailure(status),
            400 => new ShellCreateResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ShellCreateResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            _ => new ShellCreateResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static ShellCreateResponse CreateSuccess(int status, ShellCreateResponseEnvelope envelope) => new()
    {
        Status = status,
        Shell = envelope.Data,
        Location = envelope.Location
    };
}
