// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/websearch&apos; responses onto &apos;WebsearchQueryPostResponse&apos;.
/// </summary>
internal sealed class WebsearchQueryPostResponseAdapter : ResponseAdapter<WebsearchQueryPostResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private WebsearchQueryPostResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static WebsearchQueryPostResponseAdapter Instance { get; } = new WebsearchQueryPostResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override WebsearchQueryPostResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.WebsearchQueryPostResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override WebsearchQueryPostResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.WebsearchQueryPostResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new WebsearchQueryPostResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new WebsearchQueryPostResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            503 => new WebsearchQueryPostResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new WebsearchQueryPostResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static WebsearchQueryPostResponse CreateSuccess(int status, WebsearchQueryPostResponseEnvelope envelope) => new()
    {
        Status = status,
        Query = envelope.Data,
        Location = envelope.Location
    };
}
