// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/workspace&apos; responses onto &apos;WorkspaceCreateResponse&apos;.
/// </summary>
internal sealed class WorkspaceCreateResponseAdapter : ResponseAdapter<WorkspaceCreateResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["ProviderNotFoundError"];
    private static readonly string[] Status409Tags = ["ConflictError"];
    private WorkspaceCreateResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static WorkspaceCreateResponseAdapter Instance { get; } = new WorkspaceCreateResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        409 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override WorkspaceCreateResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Workspace = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.WorkspaceCreateResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override WorkspaceCreateResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new WorkspaceCreateResponse
            {
                Status = status,
                Workspace = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.WorkspaceCreateResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new WorkspaceCreateResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new WorkspaceCreateResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new WorkspaceCreateResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            409 => new WorkspaceCreateResponse(status, ReadTolerantError(rawBody, Status409Tags), rawBody),
            _ => new WorkspaceCreateResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
