// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/worktree/{projectID}/refresh&apos; responses onto &apos;WorktreeRefreshPostResponse&apos;.
/// </summary>
internal sealed class WorktreeRefreshPostResponseAdapter : ResponseAdapter<WorktreeRefreshPostResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError", "WorktreeError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private WorktreeRefreshPostResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static WorktreeRefreshPostResponseAdapter Instance { get; } = new WorktreeRefreshPostResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        204 => StatusVerdict.NoContentSuccess,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override WorktreeRefreshPostResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override WorktreeRefreshPostResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new WorktreeRefreshPostResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new WorktreeRefreshPostResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new WorktreeRefreshPostResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            _ => new WorktreeRefreshPostResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
