// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/form/request&apos; operation.
/// </summary>
public sealed record FormRequestListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<FormInfo>? _requests;
    private readonly LocationInfo? _location;
    /// <summary>
    /// Initializes a success instance of the &apos;FormRequestListResponse&apos; envelope.
    /// </summary>
    public FormRequestListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal FormRequestListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Requests = null!;
        Location = null!;
    }

    /// <summary>
    /// Gets the Requests payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<FormInfo> Requests { get => _requests ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Requests."); init => _requests = value; }
    /// <summary>
    /// Gets the location the server resolved for the request; guarded on the error path.
    /// </summary>
    public required LocationInfo Location { get => _location ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Location."); init => _location = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_requests is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Requests = ").Append(_requests);
        return true;
    }
}
