// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;GET /api/fs/find&apos; query.
/// </summary>
public sealed record FsFindRequest
{
    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    public LocationSelector? Location { get; init; }
    /// <summary>
    /// Gets the required &apos;query&apos; query value.
    /// </summary>
    public required string Query { get; init; }
    /// <summary>
    /// Gets the &apos;type&apos; query value; the server default applies when unset.
    /// </summary>
    public FsFindRequestType? Type { get; init; }
    /// <summary>
    /// Gets the &apos;limit&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Limit { get; init; }
}
