// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;GET /api/fs/read/*&apos; query.
/// </summary>
public sealed record FsReadRequest
{
    /// <summary>
    /// Gets the path the route&apos;s trailing wildcard carries; each &apos;/&apos;-separated segment is escaped as upstream&apos;s client escapes it.
    /// </summary>
    public required string Path { get; init; }
    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    public LocationSelector? Location { get; init; }
}
