// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/fs/read/*&apos; operation.
/// </summary>
public sealed record FsReadResponse : OpenCodeResponse
{
    private readonly ReadOnlyMemory<byte>? _content;
    /// <summary>
    /// Initializes a success instance of the &apos;FsReadResponse&apos; envelope.
    /// </summary>
    public FsReadResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal FsReadResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
    }

    /// <summary>
    /// Gets the Content payload; guarded on the error path.
    /// </summary>
    public required ReadOnlyMemory<byte> Content { get => _content ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Content."); init => _content = value; }
    /// <summary>
    /// Gets the Content-Type the server declared for the bytes, or null when it declared none or the response is an error.
    /// </summary>
    public string? ContentType { get; init; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_content is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Content = ").Append(_content);
        _ = builder.Append(", ContentType = ").Append(ContentType);
        return true;
    }
}
