// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/experimental/session/{sessionID}/export&apos; operation.
/// </summary>
public sealed record ExperimentalSessionExportResponse : OpenCodeResponse
{
    private readonly SessionTransferData? _sessionExport;
    /// <summary>
    /// Initializes a success instance of the &apos;ExperimentalSessionExportResponse&apos; envelope.
    /// </summary>
    public ExperimentalSessionExportResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal ExperimentalSessionExportResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        SessionExport = null!;
    }

    /// <summary>
    /// Gets the SessionExport payload; guarded on the error path.
    /// </summary>
    public required SessionTransferData SessionExport { get => _sessionExport ?? throw new InvalidOperationException("The response is an error; check IsError before accessing SessionExport."); init => _sessionExport = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_sessionExport is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("SessionExport = ").Append(_sessionExport);
        return true;
    }
}
