// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/experimental/session/{sessionID}/instructions/entries&apos; operation.
/// </summary>
public sealed record ExperimentalSessionInstructionsEntryListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<InstructionEntryInfo>? _sessionInstructionsEntry;
    /// <summary>
    /// Initializes a success instance of the &apos;ExperimentalSessionInstructionsEntryListResponse&apos; envelope.
    /// </summary>
    public ExperimentalSessionInstructionsEntryListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal ExperimentalSessionInstructionsEntryListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        SessionInstructionsEntry = null!;
    }

    /// <summary>
    /// Gets the SessionInstructionsEntry payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<InstructionEntryInfo> SessionInstructionsEntry { get => _sessionInstructionsEntry ?? throw new InvalidOperationException("The response is an error; check IsError before accessing SessionInstructionsEntry."); init => _sessionInstructionsEntry = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_sessionInstructionsEntry is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("SessionInstructionsEntry = ").Append(_sessionInstructionsEntry);
        return true;
    }
}
