// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/experimental/generate&apos; operation.
/// </summary>
public sealed record ExperimentalGenerateTextPostResponse : OpenCodeResponse
{
    private readonly ExperimentalGenerateTextPostData? _generateText;
    /// <summary>
    /// Initializes a success instance of the &apos;ExperimentalGenerateTextPostResponse&apos; envelope.
    /// </summary>
    public ExperimentalGenerateTextPostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal ExperimentalGenerateTextPostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        GenerateText = null!;
    }

    /// <summary>
    /// Gets the GenerateText payload; guarded on the error path.
    /// </summary>
    public required ExperimentalGenerateTextPostData GenerateText { get => _generateText ?? throw new InvalidOperationException("The response is an error; check IsError before accessing GenerateText."); init => _generateText = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_generateText is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("GenerateText = ").Append(_generateText);
        return true;
    }
}
