// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/server&apos; operation.
/// </summary>
public sealed record ServerResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<string>? _urls;
    /// <summary>
    /// Initializes a success instance of the &apos;ServerResponse&apos; envelope.
    /// </summary>
    public ServerResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal ServerResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Urls = null!;
    }

    /// <summary>
    /// Gets the Urls payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<string> Urls { get => _urls ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Urls."); init => _urls = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_urls is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Urls = ").Append(_urls);
        return true;
    }
}
