// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;GenerationClient&apos; collection client.
/// </summary>
public class GenerationClient
{
    private readonly Pipeline? _pipeline;
    internal GenerationClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected GenerationClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("GenerationClient", "Pipeline");

    /// <summary>
    /// Generate text. Run one stateless model generation using the server&apos;s base configuration and return the assistant text. Uses the base configuration&apos;s default model when none is specified.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;GenerateTextPostResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<GenerateTextPostResponse> GenerateTextAsync(GenerateTextPostRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Generation.GenerateText, request, OpenCodeJsonContext.Default.GenerateTextPostRequest, GenerateTextPostResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
