// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/generate&apos; operation.
/// </summary>
public sealed record GenerateTextPostResponse : OpenCodeResponse
{
    private readonly GenerateTextResponseData? _text;
    /// <summary>
    /// Initializes a success instance of the &apos;GenerateTextPostResponse&apos; envelope.
    /// </summary>
    public GenerateTextPostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal GenerateTextPostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Text = null!;
    }

    /// <summary>
    /// Gets the Text payload; guarded on the error path.
    /// </summary>
    public required GenerateTextResponseData Text { get => _text ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Text."); init => _text = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_text is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Text = ").Append(_text);
        return true;
    }
}
