// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a agent info value.
/// </summary>
public sealed record AgentInfo
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the name value.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ModelRef? Model { get; init; }

    /// <summary>
    /// Gets the request value.
    /// </summary>
    [JsonPropertyName("request")]
    public required ProviderRequestOptions Request { get; init; }

    /// <summary>
    /// Gets the system value.
    /// </summary>
    [JsonPropertyName("system")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? System { get; init; }

    /// <summary>
    /// Gets the description value.
    /// </summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }

    /// <summary>
    /// Gets the mode value.
    /// </summary>
    [JsonPropertyName("mode")]
    public required AgentInfoMode Mode { get; init; }

    /// <summary>
    /// Gets the hidden value.
    /// </summary>
    [JsonPropertyName("hidden")]
    public required bool Hidden { get; init; }

    /// <summary>
    /// Gets the color value.
    /// </summary>
    [JsonPropertyName("color")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Color { get; init; }

    /// <summary>
    /// Gets the steps value.
    /// </summary>
    [JsonPropertyName("steps")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Steps { get; init; }

    /// <summary>
    /// Gets the permissions value.
    /// </summary>
    [JsonPropertyName("permissions")]
    public required IReadOnlyList<PermissionRule> Permissions { get; init; }
}
