// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a agent not found error value.
/// </summary>
public sealed record AgentNotFoundError : IOpenCodeError
{
    /// <summary>
    /// Gets the tag value.
    /// </summary>
    [JsonPropertyName("_tag")]
    public string Tag => "AgentNotFoundError";

    /// <summary>
    /// Gets the agent id value.
    /// </summary>
    [JsonPropertyName("agentID")]
    public required string AgentId { get; init; }

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }
}
