// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported config agent mode values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<ConfigAgentMode>))]
public enum ConfigAgentMode
{
    /// <summary>
    /// Represents the &apos;subagent&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("subagent")]
    Subagent,
    /// <summary>
    /// Represents the &apos;primary&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("primary")]
    Primary,
    /// <summary>
    /// Represents the &apos;all&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("all")]
    All
}
