// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Models;
/// <summary>
/// Identifies the active arm of ConfigModelSelection.
/// </summary>
public enum ConfigModelSelectionKind
{
    /// <summary>
    /// Represents the text arm.
    /// </summary>
    Text,
    /// <summary>
    /// Represents the config model selection explicit arm.
    /// </summary>
    ConfigModelSelectionExplicit,
    /// <summary>
    /// Represents the unknown arm.
    /// </summary>
    Unknown
}
