// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config command value.
/// </summary>
public sealed record ConfigCommand
{
    /// <summary>
    /// Gets the template value.
    /// </summary>
    [JsonPropertyName("template")]
    public required string Template { get; init; }

    /// <summary>
    /// Gets the description value.
    /// </summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }

    /// <summary>
    /// Gets the agent value.
    /// </summary>
    [JsonPropertyName("agent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Agent { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ConfigModelSelection? Model { get; init; }

    /// <summary>
    /// Gets the subagent value.
    /// </summary>
    [JsonPropertyName("subagent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Subagent { get; init; }

    /// <summary>
    /// Deprecated alias for subagent.
    /// </summary>
    [JsonPropertyName("subtask")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Subtask { get; init; }
}
