// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config info watcher value.
/// </summary>
public sealed record ConfigInfoWatcher
{
    /// <summary>
    /// Gets the ignore value.
    /// </summary>
    [JsonPropertyName("ignore")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Ignore { get; init; }
}
