// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config info tool output value.
/// </summary>
public sealed record ConfigInfoToolOutput
{
    /// <summary>
    /// Gets the max lines value.
    /// </summary>
    [JsonPropertyName("max_lines")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MaxLines { get; init; }

    /// <summary>
    /// Gets the max bytes value.
    /// </summary>
    [JsonPropertyName("max_bytes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MaxBytes { get; init; }
}
