// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Models;
/// <summary>
/// Identifies the active arm of ConfigReferenceEntry.
/// </summary>
public enum ConfigReferenceEntryKind
{
    /// <summary>
    /// Represents the text arm.
    /// </summary>
    Text,
    /// <summary>
    /// Represents the config reference git arm.
    /// </summary>
    ConfigReferenceGit,
    /// <summary>
    /// Represents the config reference local arm.
    /// </summary>
    ConfigReferenceLocal,
    /// <summary>
    /// Represents the unknown arm.
    /// </summary>
    Unknown
}
