// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a experimental config update request value.
/// </summary>
public sealed record ExperimentalConfigUpdateRequest
{
    /// <summary>
    /// Gets the shell value.
    /// </summary>
    [JsonPropertyName("shell")]
    public required string? Shell { get; init; }
}
