// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a experimental session instructions entry put request value.
/// </summary>
public sealed record ExperimentalSessionInstructionsEntryPutRequest
{
    /// <summary>
    /// Gets the value value.
    /// </summary>
    [JsonPropertyName("value")]
    public required JsonElement Value { get; init; }
}
