// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a experimental migration v 1 status structural union.
/// </summary>
[JsonConverter(typeof(ExperimentalMigrationV1StatusJsonConverter))]
public sealed record ExperimentalMigrationV1Status
{
    private readonly object _value;
    private ExperimentalMigrationV1Status(ExperimentalMigrationV1StatusKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ExperimentalMigrationV1StatusKind Kind { get; }
    /// <summary>
    /// Gets the experimental migration v 1 status idle value.
    /// </summary>
    public ExperimentalMigrationV1StatusIdle ExperimentalMigrationV1StatusIdle => GetValue<ExperimentalMigrationV1StatusIdle>(ExperimentalMigrationV1StatusKind.ExperimentalMigrationV1StatusIdle);

    /// <summary>
    /// Creates a experimental migration v 1 status from its experimental migration v 1 status idle arm.
    /// </summary>
    public static ExperimentalMigrationV1Status FromExperimentalMigrationV1StatusIdle(ExperimentalMigrationV1StatusIdle value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ExperimentalMigrationV1Status(ExperimentalMigrationV1StatusKind.ExperimentalMigrationV1StatusIdle, value);
    }

    /// <summary>
    /// Gets the experimental migration v 1 status running value.
    /// </summary>
    public ExperimentalMigrationV1StatusRunning ExperimentalMigrationV1StatusRunning => GetValue<ExperimentalMigrationV1StatusRunning>(ExperimentalMigrationV1StatusKind.ExperimentalMigrationV1StatusRunning);

    /// <summary>
    /// Creates a experimental migration v 1 status from its experimental migration v 1 status running arm.
    /// </summary>
    public static ExperimentalMigrationV1Status FromExperimentalMigrationV1StatusRunning(ExperimentalMigrationV1StatusRunning value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ExperimentalMigrationV1Status(ExperimentalMigrationV1StatusKind.ExperimentalMigrationV1StatusRunning, value);
    }

    /// <summary>
    /// Gets the experimental migration v 1 status error value.
    /// </summary>
    public ExperimentalMigrationV1StatusError ExperimentalMigrationV1StatusError => GetValue<ExperimentalMigrationV1StatusError>(ExperimentalMigrationV1StatusKind.ExperimentalMigrationV1StatusError);

    /// <summary>
    /// Creates a experimental migration v 1 status from its experimental migration v 1 status error arm.
    /// </summary>
    public static ExperimentalMigrationV1Status FromExperimentalMigrationV1StatusError(ExperimentalMigrationV1StatusError value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ExperimentalMigrationV1Status(ExperimentalMigrationV1StatusKind.ExperimentalMigrationV1StatusError, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ExperimentalMigrationV1StatusKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ExperimentalMigrationV1Status FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ExperimentalMigrationV1Status(ExperimentalMigrationV1StatusKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ExperimentalMigrationV1StatusKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ExperimentalMigrationV1Status), Kind.ToString(), _value);
}
