// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a experimental migration v 1 status running value.
/// </summary>
public sealed record ExperimentalMigrationV1StatusRunning
{
    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public required string Status { get; init; }

    /// <summary>
    /// Gets the progress value.
    /// </summary>
    [JsonPropertyName("progress")]
    public required ExperimentalMigrationV1StatusRunningProgress Progress { get; init; }
}
