// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a file not found error value.
/// </summary>
public sealed record FileNotFoundError : IOpenCodeError
{
    /// <summary>
    /// Gets the tag value.
    /// </summary>
    [JsonPropertyName("_tag")]
    public string Tag => "FileNotFoundError";

    /// <summary>
    /// Gets the path value.
    /// </summary>
    [JsonPropertyName("path")]
    public required string Path { get; init; }

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }
}
