// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a file diff info value.
/// </summary>
public sealed record FileDiffInfo
{
    /// <summary>
    /// Gets the file value.
    /// </summary>
    [JsonPropertyName("file")]
    public required string File { get; init; }

    /// <summary>
    /// Gets the patch value.
    /// </summary>
    [JsonPropertyName("patch")]
    public required string Patch { get; init; }

    /// <summary>
    /// Gets the additions value.
    /// </summary>
    [JsonPropertyName("additions")]
    public required long Additions { get; init; }

    /// <summary>
    /// Gets the deletions value.
    /// </summary>
    [JsonPropertyName("deletions")]
    public required long Deletions { get; init; }

    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public required FileDiffInfoStatus Status { get; init; }
}
