// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported form when op values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<FormWhenOp>))]
public enum FormWhenOp
{
    /// <summary>
    /// Represents the &apos;eq&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("eq")]
    Eq,
    /// <summary>
    /// Represents the &apos;neq&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("neq")]
    Neq
}
