// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported form string field format values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<FormStringFieldFormat>))]
public enum FormStringFieldFormat
{
    /// <summary>
    /// Represents the &apos;email&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("email")]
    Email,
    /// <summary>
    /// Represents the &apos;uri&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("uri")]
    Uri,
    /// <summary>
    /// Represents the &apos;date&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("date")]
    Date,
    /// <summary>
    /// Represents the &apos;date-time&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("date-time")]
    DateTime
}
