// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a generate text post request value.
/// </summary>
public sealed record GenerateTextPostRequest
{
    /// <summary>
    /// Gets the prompt value.
    /// </summary>
    [JsonPropertyName("prompt")]
    public required string Prompt { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ModelRef? Model { get; init; }

    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    [JsonIgnore]
    public LocationSelector? Location { get; init; }
}
