// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a generate text response data value.
/// </summary>
public sealed record GenerateTextResponseData
{
    /// <summary>
    /// Gets the text value.
    /// </summary>
    [JsonPropertyName("text")]
    public required string Text { get; init; }
}
