// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a form field union.
/// </summary>
[JsonConverter(typeof(FormFieldJsonConverter))]
public interface IFormField
{
    /// <summary>
    /// Gets the &apos;type&apos; union marker.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; }

    /// <summary>
    /// Gets the key value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownFormField.
    /// </summary>
    [JsonPropertyName("key")]
    public string? Key { get; }

    /// <summary>
    /// Gets the title value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownFormField.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; }

    /// <summary>
    /// Gets the description value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownFormField.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; }
}
