// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a installation update available data value.
/// </summary>
public sealed record InstallationUpdateAvailableData
{
    /// <summary>
    /// Gets the version value.
    /// </summary>
    [JsonPropertyName("version")]
    public required string Version { get; init; }
}
