// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a integration command attempt status pending value.
/// </summary>
public sealed record IntegrationCommandAttemptStatusPending : IIntegrationCommandAttemptStatus
{
    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status => "pending";

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Message { get; init; }

    /// <summary>
    /// Gets the time value.
    /// </summary>
    [JsonPropertyName("time")]
    public required IntegrationCommandAttemptStatusPendingTime Time { get; init; }
}
