// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a plugin info union.
/// </summary>
[JsonConverter(typeof(PluginInfoJsonConverter))]
public interface IPluginInfo
{
    /// <summary>
    /// Gets the &apos;status&apos; union marker.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; }
}
