// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session event durable union.
/// </summary>
[JsonConverter(typeof(SessionEventDurableJsonConverter))]
public interface ISessionEventDurable : ISessionLogItem
{
    /// <summary>
    /// Gets the id value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownSessionEventDurable.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; }

    /// <summary>
    /// Gets the created value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownSessionEventDurable.
    /// </summary>
    [JsonPropertyName("created")]
    public double? Created { get; }

    /// <summary>
    /// Gets the metadata value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownSessionEventDurable.
    /// </summary>
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, JsonElement>? Metadata { get; }

    /// <summary>
    /// Gets the durable value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownSessionEventDurable.
    /// </summary>
    [JsonPropertyName("durable")]
    public IDurableEnvelope? Durable { get; }

    /// <summary>
    /// Gets the location value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownSessionEventDurable.
    /// </summary>
    [JsonPropertyName("location")]
    public LocationRef? Location { get; }
}
