// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session inbox info union.
/// </summary>
[JsonConverter(typeof(SessionInboxInfoJsonConverter))]
public interface ISessionInboxInfo
{
    /// <summary>
    /// Gets the &apos;type&apos; union marker.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; }
}
