// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session message compaction union.
/// </summary>
[JsonConverter(typeof(SessionMessageCompactionJsonConverter))]
public interface ISessionMessageCompaction : ISessionMessageInfo
{
    /// <summary>
    /// Gets the &apos;status&apos; union marker.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; }

    /// <summary>
    /// Gets the time value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownSessionMessageCompaction.
    /// </summary>
    [JsonPropertyName("time")]
    public ISessionMessageCompactionTime? Time { get; }
}
