// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session event durable union.
/// </summary>
[JsonConverter(typeof(SessionEventDurableJsonConverter))]
public interface ISessionEventDurable : ISessionLogItem
{
}
