// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a mcp add put request value.
/// </summary>
public sealed record McpAddPutRequest
{
    /// <summary>
    /// Gets the config value.
    /// </summary>
    [JsonPropertyName("config")]
    public required IMcp Config { get; init; }

    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    [JsonIgnore]
    public LocationSelector? Location { get; init; }
}
