// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Models;
/// <summary>
/// Identifies the active arm of McpRemoteConfigOauth.
/// </summary>
public enum McpRemoteConfigOauthKind
{
    /// <summary>
    /// Represents the mcp o auth config arm.
    /// </summary>
    McpOAuthConfig,
    /// <summary>
    /// Represents the boolean arm.
    /// </summary>
    Boolean,
    /// <summary>
    /// Represents the unknown arm.
    /// </summary>
    Unknown
}
