// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a mcp status disabled value.
/// </summary>
public sealed record McpStatusDisabled : IMcpStatus
{
    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status => "disabled";
}
