// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a mcp status changed data value.
/// </summary>
public sealed record McpStatusChangedData
{
    /// <summary>
    /// Gets the server value.
    /// </summary>
    [JsonPropertyName("server")]
    public required string Server { get; init; }
}
