// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported message list request type values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<MessageListRequestType>))]
public enum MessageListRequestType
{
    /// <summary>
    /// Represents the &apos;agent-switched&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("agent-switched")]
    AgentSwitched,
    /// <summary>
    /// Represents the &apos;model-switched&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("model-switched")]
    ModelSwitched,
    /// <summary>
    /// Represents the &apos;location-switched&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("location-switched")]
    LocationSwitched,
    /// <summary>
    /// Represents the &apos;user&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("user")]
    User,
    /// <summary>
    /// Represents the &apos;synthetic&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("synthetic")]
    Synthetic,
    /// <summary>
    /// Represents the &apos;system&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("system")]
    System,
    /// <summary>
    /// Represents the &apos;skill&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("skill")]
    Skill,
    /// <summary>
    /// Represents the &apos;shell&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("shell")]
    Shell,
    /// <summary>
    /// Represents the &apos;assistant&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("assistant")]
    Assistant,
    /// <summary>
    /// Represents the &apos;compaction&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("compaction")]
    Compaction
}
