// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a model info limit value.
/// </summary>
public sealed record ModelInfoLimit
{
    /// <summary>
    /// Gets the context value.
    /// </summary>
    [JsonPropertyName("context")]
    public required long Context { get; init; }

    /// <summary>
    /// Gets the input value.
    /// </summary>
    [JsonPropertyName("input")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Input { get; init; }

    /// <summary>
    /// Gets the output value.
    /// </summary>
    [JsonPropertyName("output")]
    public required long Output { get; init; }
}
