// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a pairing code value.
/// </summary>
public sealed record PairingCode
{
    /// <summary>
    /// Gets the code value.
    /// </summary>
    [JsonPropertyName("code")]
    public required string Code { get; init; }

    /// <summary>
    /// Gets the expires in value.
    /// </summary>
    [JsonPropertyName("expires_in")]
    public required long ExpiresIn { get; init; }

    /// <summary>
    /// Prints the record&apos;s members with its secret members masked.
    /// </summary>
    public override string ToString() => RecordPrinter.Format(nameof(PairingCode), ("Code", RecordPrinter.Redact(Code)), ("ExpiresIn", ExpiresIn));
}
