// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a persistent pty handoff value.
/// </summary>
public sealed record PersistentPtyHandoff
{
    /// <summary>
    /// Gets the directory value.
    /// </summary>
    [JsonPropertyName("directory")]
    public required string Directory { get; init; }

    /// <summary>
    /// Gets the instance id value.
    /// </summary>
    [JsonPropertyName("instanceID")]
    public required string InstanceId { get; init; }

    /// <summary>
    /// Gets the ticket value.
    /// </summary>
    [JsonPropertyName("ticket")]
    public required string Ticket { get; init; }

    /// <summary>
    /// Gets the expires at value.
    /// </summary>
    [JsonPropertyName("expiresAt")]
    [JsonNumberHandling(JsonNumberHandling.AllowNamedFloatingPointLiterals)]
    public required double ExpiresAt { get; init; }
}
