// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a persistent pty update input size value.
/// </summary>
public sealed record PersistentPtyUpdateInputSize
{
    /// <summary>
    /// Gets the cols value.
    /// </summary>
    [JsonPropertyName("cols")]
    public required long Cols { get; init; }

    /// <summary>
    /// Gets the rows value.
    /// </summary>
    [JsonPropertyName("rows")]
    public required long Rows { get; init; }
}
