// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a persistent pty info value.
/// </summary>
public sealed record PersistentPtyInfo
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the title value.
    /// </summary>
    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>
    /// Gets the command value.
    /// </summary>
    [JsonPropertyName("command")]
    public required string Command { get; init; }

    /// <summary>
    /// Gets the args value.
    /// </summary>
    [JsonPropertyName("args")]
    public required IReadOnlyList<string> Args { get; init; }

    /// <summary>
    /// Gets the cwd value.
    /// </summary>
    [JsonPropertyName("cwd")]
    public required string Cwd { get; init; }

    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public required PersistentPtyInfoStatus Status { get; init; }

    /// <summary>
    /// Gets the pid value.
    /// </summary>
    [JsonPropertyName("pid")]
    public required long Pid { get; init; }

    /// <summary>
    /// Gets the exit code value.
    /// </summary>
    [JsonPropertyName("exitCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ExitCode { get; init; }

    /// <summary>
    /// Gets the session id value.
    /// </summary>
    [JsonPropertyName("sessionID")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Gets the foreground process value.
    /// </summary>
    [JsonPropertyName("foregroundProcess")]
    public required string? ForegroundProcess { get; init; }

    /// <summary>
    /// Gets the size value.
    /// </summary>
    [JsonPropertyName("size")]
    public required PersistentPtyInfoSize Size { get; init; }

    /// <summary>
    /// Gets the output value.
    /// </summary>
    [JsonPropertyName("output")]
    public required PersistentPtyInfoOutput Output { get; init; }
}
