// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a provider settings timeout structural union.
/// </summary>
[JsonConverter(typeof(ProviderSettingsTimeoutJsonConverter))]
public sealed record ProviderSettingsTimeout
{
    private readonly object _value;
    private ProviderSettingsTimeout(ProviderSettingsTimeoutKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ProviderSettingsTimeoutKind Kind { get; }
    /// <summary>
    /// Gets the number value.
    /// </summary>
    public double Number => GetValue<double>(ProviderSettingsTimeoutKind.Number);

    /// <summary>
    /// Creates a provider settings timeout from its number arm.
    /// </summary>
    public static ProviderSettingsTimeout FromNumber(double value)
    {
        return new ProviderSettingsTimeout(ProviderSettingsTimeoutKind.Number, value);
    }

    /// <summary>
    /// Gets the boolean value.
    /// </summary>
    public bool Boolean => GetValue<bool>(ProviderSettingsTimeoutKind.Boolean);

    /// <summary>
    /// Creates a provider settings timeout from its boolean arm.
    /// </summary>
    public static ProviderSettingsTimeout FromBoolean(bool value)
    {
        return new ProviderSettingsTimeout(ProviderSettingsTimeoutKind.Boolean, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ProviderSettingsTimeoutKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ProviderSettingsTimeout FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ProviderSettingsTimeout(ProviderSettingsTimeoutKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ProviderSettingsTimeoutKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ProviderSettingsTimeout), Kind.ToString(), _value);
}
