// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a provider compaction provider value.
/// </summary>
public sealed record ProviderCompactionProvider : IProviderCompaction
{
    /// <summary>
    /// Gets the mode value.
    /// </summary>
    [JsonPropertyName("mode")]
    public string Mode => "provider";

    /// <summary>
    /// Gets the threshold value.
    /// </summary>
    [JsonPropertyName("threshold")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Threshold { get; init; }
}
