// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a pty ticket connect token value.
/// </summary>
public sealed record PtyTicketConnectToken
{
    /// <summary>
    /// Gets the ticket value.
    /// </summary>
    [JsonPropertyName("ticket")]
    public required string Ticket { get; init; }

    /// <summary>
    /// Gets the expires in value.
    /// </summary>
    [JsonPropertyName("expires_in")]
    public required long ExpiresIn { get; init; }
}
