// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a pty updated data value.
/// </summary>
public sealed record PtyUpdatedData
{
    /// <summary>
    /// Gets the info value.
    /// </summary>
    [JsonPropertyName("info")]
    public required Pty Info { get; init; }
}
