// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a question option value.
/// </summary>
public sealed record QuestionOption
{
    /// <summary>
    /// Display text (1-5 words, concise)
    /// </summary>
    [JsonPropertyName("label")]
    public required string Label { get; init; }

    /// <summary>
    /// Explanation of choice
    /// </summary>
    [JsonPropertyName("description")]
    public required string Description { get; init; }
}
