// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a question replied data value.
/// </summary>
public sealed record QuestionRepliedData
{
    /// <summary>
    /// Gets the session id value.
    /// </summary>
    [JsonPropertyName("sessionID")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Gets the request id value.
    /// </summary>
    [JsonPropertyName("requestID")]
    public required string RequestId { get; init; }

    /// <summary>
    /// Gets the answers value.
    /// </summary>
    [JsonPropertyName("answers")]
    public required IReadOnlyList<IReadOnlyList<string>> Answers { get; init; }
}
