// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a question info value.
/// </summary>
public sealed record QuestionInfo
{
    /// <summary>
    /// Complete question
    /// </summary>
    [JsonPropertyName("question")]
    public required string Question { get; init; }

    /// <summary>
    /// Very short label (max 30 chars)
    /// </summary>
    [JsonPropertyName("header")]
    public required string Header { get; init; }

    /// <summary>
    /// Available choices
    /// </summary>
    [JsonPropertyName("options")]
    public required IReadOnlyList<QuestionOption> Options { get; init; }

    /// <summary>
    /// Gets the multiple value.
    /// </summary>
    [JsonPropertyName("multiple")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Multiple { get; init; }

    /// <summary>
    /// Gets the custom value.
    /// </summary>
    [JsonPropertyName("custom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Custom { get; init; }
}
