// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a service unavailable error value.
/// </summary>
public sealed record ServiceUnavailableError : IOpenCodeError
{
    /// <summary>
    /// Gets the tag value.
    /// </summary>
    [JsonPropertyName("_tag")]
    public string Tag => "ServiceUnavailableError";

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }

    /// <summary>
    /// Gets the service value.
    /// </summary>
    [JsonPropertyName("service")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Service { get; init; }
}
