// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a server info paths value.
/// </summary>
public sealed record ServerInfoPaths
{
    /// <summary>
    /// Gets the tmp value.
    /// </summary>
    [JsonPropertyName("tmp")]
    public required string Tmp { get; init; }
}
