// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session inbox move time value.
/// </summary>
public sealed record SessionInboxMoveTime : ISessionInboxInfoTime
{
    /// <summary>
    /// Gets the created value.
    /// </summary>
    [JsonPropertyName("created")]
    public required double Created { get; init; }
}
