// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session skill post request value.
/// </summary>
public sealed record SessionSkillPostRequest
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Id { get; init; }

    /// <summary>
    /// Gets the skill value.
    /// </summary>
    [JsonPropertyName("skill")]
    public required string Skill { get; init; }

    /// <summary>
    /// Gets the resume value.
    /// </summary>
    [JsonPropertyName("resume")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Resume { get; init; }
}
