// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session message idle value.
/// </summary>
public sealed record SessionMessageIdle : ISessionMessageInfo
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, JsonElement>? Metadata { get; init; }

    /// <summary>
    /// Gets the time value.
    /// </summary>
    [JsonPropertyName("time")]
    public required SessionMessageIdleTime Time { get; init; }

    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "idle";

    /// <summary>
    /// Gets the outcome value.
    /// </summary>
    [JsonPropertyName("outcome")]
    public required SessionMessageIdleOutcome Outcome { get; init; }
}
