// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session fork boundary before value.
/// </summary>
public sealed record SessionForkBoundaryBefore : SessionForkBoundary
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public override string Type => "before";

    /// <summary>
    /// Gets the message id value.
    /// </summary>
    [JsonPropertyName("messageID")]
    public required string MessageId { get; init; }
}
