// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session stats info value.
/// </summary>
public sealed record SessionStatsInfo
{
    /// <summary>
    /// Gets the range value.
    /// </summary>
    [JsonPropertyName("range")]
    public required SessionStatsInfoRange Range { get; init; }

    /// <summary>
    /// Gets the sessions value.
    /// </summary>
    [JsonPropertyName("sessions")]
    public required long Sessions { get; init; }

    /// <summary>
    /// Gets the subagents value.
    /// </summary>
    [JsonPropertyName("subagents")]
    public required long Subagents { get; init; }

    /// <summary>
    /// Gets the prompts value.
    /// </summary>
    [JsonPropertyName("prompts")]
    public required long Prompts { get; init; }

    /// <summary>
    /// Gets the steps value.
    /// </summary>
    [JsonPropertyName("steps")]
    public required long Steps { get; init; }

    /// <summary>
    /// Gets the tokens value.
    /// </summary>
    [JsonPropertyName("tokens")]
    public required TokenUsageInfo Tokens { get; init; }

    /// <summary>
    /// Gets the cost value.
    /// </summary>
    [JsonPropertyName("cost")]
    public required double Cost { get; init; }

    /// <summary>
    /// Gets the tools value.
    /// </summary>
    [JsonPropertyName("tools")]
    public required ISessionStatsTools Tools { get; init; }

    /// <summary>
    /// Gets the active days value.
    /// </summary>
    [JsonPropertyName("activeDays")]
    public required long ActiveDays { get; init; }

    /// <summary>
    /// Gets the streak value.
    /// </summary>
    [JsonPropertyName("streak")]
    public required long Streak { get; init; }

    /// <summary>
    /// Gets the activity value.
    /// </summary>
    [JsonPropertyName("activity")]
    public required IReadOnlyList<SessionStatsActivity> Activity { get; init; }

    /// <summary>
    /// Gets the models value.
    /// </summary>
    [JsonPropertyName("models")]
    public required IReadOnlyList<SessionStatsModelUsage> Models { get; init; }
}
