// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session inbox item compaction value.
/// </summary>
public sealed record SessionInboxItemCompaction : ISessionInboxItem
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "compaction";

    /// <summary>
    /// Gets the payload value.
    /// </summary>
    [JsonPropertyName("payload")]
    public required IReadOnlyDictionary<string, JsonElement?> Payload { get; init; }

    /// <summary>
    /// Gets the delivery value.
    /// </summary>
    [JsonPropertyName("delivery")]
    public required SessionInboxDelivery Delivery { get; init; }
}
