// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported session stats request tools values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<SessionStatsRequestTools>))]
public enum SessionStatsRequestTools
{
    /// <summary>
    /// Represents the &apos;none&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("none")]
    None,
    /// <summary>
    /// Represents the &apos;summary&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("summary")]
    Summary,
    /// <summary>
    /// Represents the &apos;detail&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("detail")]
    Detail
}
