// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session inbox item user value.
/// </summary>
public sealed record SessionInboxItemUser : ISessionInboxItem
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "user";

    /// <summary>
    /// Gets the payload value.
    /// </summary>
    [JsonPropertyName("payload")]
    public required SessionInboxUserPayload Payload { get; init; }

    /// <summary>
    /// Gets the delivery value.
    /// </summary>
    [JsonPropertyName("delivery")]
    public required SessionInboxDelivery Delivery { get; init; }
}
