// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session move post request value.
/// </summary>
public sealed record SessionMovePostRequest
{
    /// <summary>
    /// Gets the directory value.
    /// </summary>
    [JsonPropertyName("directory")]
    public required string Directory { get; init; }

    /// <summary>
    /// Gets the workspace id value.
    /// </summary>
    [JsonPropertyName("workspaceID")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? WorkspaceId { get; init; }

    /// <summary>
    /// Gets the delivery value.
    /// </summary>
    [JsonPropertyName("delivery")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SessionInboxDelivery? Delivery { get; init; }
}
