// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported session execution interrupted data reason values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<SessionExecutionInterruptedDataReason>))]
public enum SessionExecutionInterruptedDataReason
{
    /// <summary>
    /// Represents the &apos;user&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("user")]
    User,
    /// <summary>
    /// Represents the &apos;shutdown&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("shutdown")]
    Shutdown,
    /// <summary>
    /// Represents the &apos;superseded&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("superseded")]
    Superseded
}
