// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported session compaction failed data reason values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<SessionCompactionFailedDataReason>))]
public enum SessionCompactionFailedDataReason
{
    /// <summary>
    /// Represents the &apos;auto&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("auto")]
    Auto,
    /// <summary>
    /// Represents the &apos;manual&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("manual")]
    Manual
}
