// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session environment put request value.
/// </summary>
public sealed record SessionEnvironmentPutRequest
{
    /// <summary>
    /// Gets the variables value.
    /// </summary>
    [JsonPropertyName("variables")]
    public required IReadOnlyDictionary<string, string> Variables { get; init; }
}
