// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session question reply post request value.
/// </summary>
public sealed record SessionQuestionReplyPostRequest
{
    /// <summary>
    /// User answers in order of questions (each answer is an array of selected labels)
    /// </summary>
    [JsonPropertyName("answers")]
    public required IReadOnlyList<IReadOnlyList<string>> Answers { get; init; }
}
