// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session status busy value.
/// </summary>
public sealed record SessionStatusBusy : ISessionStatus
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "busy";
}
