// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session synthetic post request value.
/// </summary>
public sealed record SessionSyntheticPostRequest
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Id { get; init; }

    /// <summary>
    /// Gets the text value.
    /// </summary>
    [JsonPropertyName("text")]
    public required string Text { get; init; }

    /// <summary>
    /// Gets the description value.
    /// </summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Description { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, JsonElement>? Metadata { get; init; }

    /// <summary>
    /// Gets the delivery value.
    /// </summary>
    [JsonPropertyName("delivery")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfSessionInboxDeliveryJsonConverter))]
    public Optional<SessionInboxDelivery?> Delivery { get; init; }

    /// <summary>
    /// Gets the resume value.
    /// </summary>
    [JsonPropertyName("resume")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfBooleanJsonConverter))]
    public Optional<bool?> Resume { get; init; }
}
