// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Collections.ObjectModel;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session compaction ended value.
/// </summary>
public sealed record SessionCompactionEnded : ISessionEventDurable
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the created value.
    /// </summary>
    [JsonPropertyName("created")]
    public required double Created { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, JsonElement> Metadata { get; init => field = OptionalCollectionInput.Normalize(value, field, static input => new ReadOnlyDictionary<string, JsonElement>(input.ToDictionary(static pair => pair.Key, static pair => pair.Value, StringComparer.Ordinal))); } = new ReadOnlyDictionary<string, JsonElement>(new Dictionary<string, JsonElement>(StringComparer.Ordinal));

    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "session.compaction.ended";

    /// <summary>
    /// Gets the durable value.
    /// </summary>
    [JsonPropertyName("durable")]
    public required SessionCompactionEndedDurable Durable { get; init; }

    /// <summary>
    /// Gets the location value.
    /// </summary>
    [JsonPropertyName("location")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(WireNullRejectingJsonConverter<LocationRef>))]
    public LocationRef? Location { get; init; }

    /// <summary>
    /// Gets the data value.
    /// </summary>
    [JsonPropertyName("data")]
    public required SessionCompactionEndedData Data { get; init; }
}
