// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session compaction ended data value.
/// </summary>
public sealed record SessionCompactionEndedData
{
    /// <summary>
    /// Gets the session id value.
    /// </summary>
    [JsonPropertyName("sessionID")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Gets the reason value.
    /// </summary>
    [JsonPropertyName("reason")]
    public required SessionCompactionEndedDataReason Reason { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ModelRef? Model { get; init; }

    /// <summary>
    /// Gets the provider state value.
    /// </summary>
    [JsonPropertyName("providerState")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, JsonElement>? ProviderState { get; init; }

    /// <summary>
    /// Gets the provider context value.
    /// </summary>
    [JsonPropertyName("providerContext")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SessionProviderContext? ProviderContext { get; init; }

    /// <summary>
    /// Gets the text value.
    /// </summary>
    [JsonPropertyName("text")]
    public required string Text { get; init; }

    /// <summary>
    /// Gets the recent value.
    /// </summary>
    [JsonPropertyName("recent")]
    public required string Recent { get; init; }

    /// <summary>
    /// Gets the cost value.
    /// </summary>
    [JsonPropertyName("cost")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Cost { get; init; }

    /// <summary>
    /// Gets the tokens value.
    /// </summary>
    [JsonPropertyName("tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TokenUsageInfo? Tokens { get; init; }
}
