// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported session usage recorded data source values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<SessionUsageRecordedDataSource>))]
public enum SessionUsageRecordedDataSource
{
    /// <summary>
    /// Represents the &apos;title&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("title")]
    Title,
    /// <summary>
    /// Represents the &apos;compaction&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("compaction")]
    Compaction
}
