// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session compact request value.
/// </summary>
public sealed record SessionCompactRequest
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Id { get; init; }

    /// <summary>
    /// Gets the delivery value.
    /// </summary>
    [JsonPropertyName("delivery")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfSessionInboxDeliveryJsonConverter))]
    public Optional<SessionInboxDelivery?> Delivery { get; init; }
}
