// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session step failed data value.
/// </summary>
public sealed record SessionStepFailedData
{
    /// <summary>
    /// Gets the session id value.
    /// </summary>
    [JsonPropertyName("sessionID")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Gets the assistant message id value.
    /// </summary>
    [JsonPropertyName("assistantMessageID")]
    public required string AssistantMessageId { get; init; }

    /// <summary>
    /// Gets the error value.
    /// </summary>
    [JsonPropertyName("error")]
    public required SessionStructuredError Error { get; init; }

    /// <summary>
    /// Gets the cost value.
    /// </summary>
    [JsonPropertyName("cost")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(WireNullRejectingValueJsonConverter<double>))]
    public double? Cost { get; init; }

    /// <summary>
    /// Gets the tokens value.
    /// </summary>
    [JsonPropertyName("tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(WireNullRejectingJsonConverter<TokenUsageInfo>))]
    public TokenUsageInfo? Tokens { get; init; }

    /// <summary>
    /// Gets the snapshot value.
    /// </summary>
    [JsonPropertyName("snapshot")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(WireNullRejectingJsonConverter<string>))]
    public string? Snapshot { get; init; }

    /// <summary>
    /// Gets the files value.
    /// </summary>
    [JsonPropertyName("files")]
    public IReadOnlyList<string> Files { get; init => field = OptionalCollectionInput.Normalize(value, field, static input => new List<string>(input).AsReadOnly()); } = [];
}
