// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session message assistant snapshot value.
/// </summary>
public sealed record SessionMessageAssistantSnapshot
{
    /// <summary>
    /// Gets the start value.
    /// </summary>
    [JsonPropertyName("start")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Start { get; init; }

    /// <summary>
    /// Gets the end value.
    /// </summary>
    [JsonPropertyName("end")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? End { get; init; }

    /// <summary>
    /// Gets the files value.
    /// </summary>
    [JsonPropertyName("files")]
    public IReadOnlyList<string> Files
    {
        get;
        init
        {
            // Source-generated deserialization passes null for an absent optional init-only collection.
            field = value is null ? Array.Empty<string>() : new List<string>(value).AsReadOnly();
        }
    } = [];
}
