// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session stats tools detail value.
/// </summary>
public sealed record SessionStatsToolsDetail : ISessionStatsTools
{
    /// <summary>
    /// Gets the mode value.
    /// </summary>
    [JsonPropertyName("mode")]
    public string Mode => "detail";

    /// <summary>
    /// Gets the totals value.
    /// </summary>
    [JsonPropertyName("totals")]
    public required SessionStatsToolTotals Totals { get; init; }

    /// <summary>
    /// Gets the usage value.
    /// </summary>
    [JsonPropertyName("usage")]
    public required IReadOnlyList<SessionStatsToolUsage> Usage { get; init; }
}
