// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session renamed durable value.
/// </summary>
public sealed record SessionRenamedDurable
{
    /// <summary>
    /// Gets the aggregate id value.
    /// </summary>
    [JsonPropertyName("aggregateID")]
    public required string AggregateId { get; init; }

    /// <summary>
    /// Gets the seq value.
    /// </summary>
    [JsonPropertyName("seq")]
    public required long Seq { get; init; }

    /// <summary>
    /// Gets the version value.
    /// </summary>
    [JsonPropertyName("version")]
    public required double Version { get; init; }
}
