// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session info value.
/// </summary>
public sealed record SessionInfo
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the parent id value.
    /// </summary>
    [JsonPropertyName("parentID")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ParentId { get; init; }

    /// <summary>
    /// Gets the fork value.
    /// </summary>
    [JsonPropertyName("fork")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SessionInfoFork? Fork { get; init; }

    /// <summary>
    /// Gets the project id value.
    /// </summary>
    [JsonPropertyName("projectID")]
    public required string ProjectId { get; init; }

    /// <summary>
    /// Gets the agent value.
    /// </summary>
    [JsonPropertyName("agent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Agent { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ModelRef? Model { get; init; }

    /// <summary>
    /// Gets the cost value.
    /// </summary>
    [JsonPropertyName("cost")]
    public required double Cost { get; init; }

    /// <summary>
    /// Gets the tokens value.
    /// </summary>
    [JsonPropertyName("tokens")]
    public required TokenUsageInfo Tokens { get; init; }

    /// <summary>
    /// Gets the time value.
    /// </summary>
    [JsonPropertyName("time")]
    public required SessionInfoTime Time { get; init; }

    /// <summary>
    /// Gets the title value.
    /// </summary>
    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Title { get; init; }

    /// <summary>
    /// Gets the location value.
    /// </summary>
    [JsonPropertyName("location")]
    public required LocationRef Location { get; init; }

    /// <summary>
    /// Gets the subpath value.
    /// </summary>
    [JsonPropertyName("subpath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Subpath { get; init; }

    /// <summary>
    /// Gets the revert value.
    /// </summary>
    [JsonPropertyName("revert")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SessionRevert? Revert { get; init; }
}
