// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session rename request value.
/// </summary>
public sealed record SessionRenameRequest
{
    /// <summary>
    /// Gets the title value.
    /// </summary>
    [JsonPropertyName("title")]
    public required string Title { get; init; }
}
