// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session model selected data value.
/// </summary>
public sealed record SessionModelSelectedData
{
    /// <summary>
    /// Gets the session id value.
    /// </summary>
    [JsonPropertyName("sessionID")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    public required ModelRef Model { get; init; }

    /// <summary>
    /// Gets the previous value.
    /// </summary>
    [JsonPropertyName("previous")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ModelRef? Previous { get; init; }
}
