// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Collections.ObjectModel;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session message compaction running value.
/// </summary>
public sealed record SessionMessageCompactionRunning : SessionMessageCompaction
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public override string Type => "compaction";

    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, JsonElement> Metadata { get; init => field = OptionalCollectionInput.Normalize(value, field, static input => new ReadOnlyDictionary<string, JsonElement>(input.ToDictionary(static pair => pair.Key, static pair => pair.Value, StringComparer.Ordinal))); } = new ReadOnlyDictionary<string, JsonElement>(new Dictionary<string, JsonElement>(StringComparer.Ordinal));

    /// <summary>
    /// Gets the time value.
    /// </summary>
    [JsonPropertyName("time")]
    public required SessionMessageCompactionRunningTime Time { get; init; }

    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public override string Status => "running";

    /// <summary>
    /// Gets the reason value.
    /// </summary>
    [JsonPropertyName("reason")]
    public required SessionMessageCompactionRunningReason Reason { get; init; }

    /// <summary>
    /// Gets the summary value.
    /// </summary>
    [JsonPropertyName("summary")]
    public required string Summary { get; init; }

    /// <summary>
    /// Gets the recent value.
    /// </summary>
    [JsonPropertyName("recent")]
    public required string Recent { get; init; }
}
