// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session metadata updated data value.
/// </summary>
public sealed record SessionMetadataUpdatedData
{
    /// <summary>
    /// Gets the session id value.
    /// </summary>
    [JsonPropertyName("sessionID")]
    public required string SessionId { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    public required IReadOnlyDictionary<string, JsonElement> Metadata { get; init; }
}
