// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session status retry value.
/// </summary>
public sealed record SessionStatusRetry : ISessionStatus
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "retry";

    /// <summary>
    /// Gets the attempt value.
    /// </summary>
    [JsonPropertyName("attempt")]
    public required long Attempt { get; init; }

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }

    /// <summary>
    /// Gets the action value.
    /// </summary>
    [JsonPropertyName("action")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SessionStatusRetryAction? Action { get; init; }

    /// <summary>
    /// Gets the next value.
    /// </summary>
    [JsonPropertyName("next")]
    public required long Next { get; init; }
}
