// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a shell not found error value.
/// </summary>
public sealed record ShellNotFoundError : OpenCodeError
{
    /// <summary>
    /// Gets the tag value.
    /// </summary>
    [JsonPropertyName("_tag")]
    public override string Tag => "ShellNotFoundError";

    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }
}
