// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a shell info value.
/// </summary>
public sealed record ShellInfo
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public required ShellInfoStatus Status { get; init; }

    /// <summary>
    /// Gets the command value.
    /// </summary>
    [JsonPropertyName("command")]
    public required string Command { get; init; }

    /// <summary>
    /// Gets the cwd value.
    /// </summary>
    [JsonPropertyName("cwd")]
    public required string Cwd { get; init; }

    /// <summary>
    /// Gets the shell value.
    /// </summary>
    [JsonPropertyName("shell")]
    public required string Shell { get; init; }

    /// <summary>
    /// Gets the file value.
    /// </summary>
    [JsonPropertyName("file")]
    public required string File { get; init; }

    /// <summary>
    /// Gets the pid value.
    /// </summary>
    [JsonPropertyName("pid")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Pid { get; init; }

    /// <summary>
    /// Gets the exit value.
    /// </summary>
    [JsonPropertyName("exit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Exit { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    public required IReadOnlyDictionary<string, JsonElement?> Metadata { get; init; }

    /// <summary>
    /// Gets the time value.
    /// </summary>
    [JsonPropertyName("time")]
    public required ShellInfoTime Time { get; init; }
}
