// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a token usage info cache value.
/// </summary>
public sealed record TokenUsageInfoCache
{
    /// <summary>
    /// Gets the read value.
    /// </summary>
    [JsonPropertyName("read")]
    public required double Read { get; init; }

    /// <summary>
    /// Gets the write value.
    /// </summary>
    [JsonPropertyName("write")]
    public required double Write { get; init; }
}
