// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Preserves an unknown form state payload.
/// </summary>
[JsonConverter(typeof(UnknownFormStateJsonConverter))]
public sealed record UnknownFormState : IFormState
{
    private readonly string _marker;
    /// <summary>
    /// Initializes an unknown union value from its marker and raw payload.
    /// </summary>
    [JsonConstructor]
    public UnknownFormState(string status, JsonElement payload)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(status);
        if (payload.ValueKind is JsonValueKind.Undefined)
        {
            throw new ArgumentException("The payload must be a parsed JSON element.", nameof(payload));
        }

        UnionPayloadGuard.Instance.RequireString(payload, "status", status);
        _marker = status;
        Payload = payload.Clone();
    }

    /// <summary>
    /// Gets the unrecognized &apos;status&apos; marker.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status => _marker;
    /// <summary>
    /// Gets the preserved raw JSON payload.
    /// </summary>
    public JsonElement Payload { get; }
}
