// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Preserves an unknown session message payload.
/// </summary>
public sealed record UnknownSessionMessage : SessionMessage
{
    private readonly string _marker;
    /// <summary>
    /// Initializes an unknown union value from its marker and raw payload.
    /// </summary>
    [JsonConstructor]
    public UnknownSessionMessage(string type, JsonElement payload)
    {
        ArgumentException.ThrowIfNullOrEmpty(type);
        _marker = type;
        Payload = payload.Clone();
    }

    /// <summary>
    /// Gets the unrecognized &apos;type&apos; marker.
    /// </summary>
    public override string Type => _marker;
    /// <summary>
    /// Gets the preserved raw JSON payload.
    /// </summary>
    public JsonElement Payload { get; }
}
