// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported vcs base source values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<VcsBaseSource>))]
public enum VcsBaseSource
{
    /// <summary>
    /// Represents the &apos;reflog&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("reflog")]
    Reflog,
    /// <summary>
    /// Represents the &apos;default&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("default")]
    Default
}
