// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported vcs mode values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<VcsMode>))]
public enum VcsMode
{
    /// <summary>
    /// Represents the &apos;working&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("working")]
    Working,
    /// <summary>
    /// Represents the &apos;branch&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("branch")]
    Branch,
    /// <summary>
    /// Represents the &apos;committed&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("committed")]
    Committed
}
