// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a workspace create request value.
/// </summary>
public sealed record WorkspaceCreateRequest
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Id { get; init; }

    /// <summary>
    /// Gets the provider value.
    /// </summary>
    [JsonPropertyName("provider")]
    public required string Provider { get; init; }
}
