// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/debug/location&apos; operation.
/// </summary>
public sealed record DebugLocationListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<LocationRef>? _locations;
    /// <summary>
    /// Initializes a success instance of the &apos;DebugLocationListResponse&apos; envelope.
    /// </summary>
    public DebugLocationListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal DebugLocationListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Locations = null!;
    }

    /// <summary>
    /// Gets the Locations payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<LocationRef> Locations { get => _locations ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Locations."); init => _locations = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_locations is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Locations = ").Append(_locations);
        return true;
    }
}
