// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.StreamAdapters;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;EventsClient&apos; collection client.
/// </summary>
public class EventsClient
{
    private readonly Pipeline? _pipeline;
    internal EventsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected EventsClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("EventsClient", "Pipeline");

    /// <summary>
    /// Subscribe to events. Subscribe to native events and plugin RPC events across all server locations. Volatile by contract: a slow consumer overflows and fails the stream, and events during disconnection are missed.
    /// </summary>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IEvent&apos; stream.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned a declared error status (declared: 400, 401); streaming API errors always throw.</exception>
    /// <exception cref = "OpenCodeStreamFailureException">The opened stream reported a schema-valid failure with a typed cause.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached, the stream could not be read, or a frame or failure cause was malformed.</exception>
    public virtual IAsyncEnumerable<IEvent> SubscribeAsync(CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteStreamAsync(HttpMethod.Get, OpenCodeRoutes.Events.Subscribe, EventSubscribeResponseStreamAdapter.Instance, cancellationToken);
    }
}
