// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/workspace&apos; operation.
/// </summary>
public sealed record WorkspaceCreateResponse : OpenCodeResponse
{
    private readonly string? _workspace;
    /// <summary>
    /// Initializes a success instance of the &apos;WorkspaceCreateResponse&apos; envelope.
    /// </summary>
    public WorkspaceCreateResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal WorkspaceCreateResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Workspace = null!;
    }

    /// <summary>
    /// Gets the Workspace payload; guarded on the error path.
    /// </summary>
    public required string Workspace { get => _workspace ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Workspace."); init => _workspace = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_workspace is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Workspace = ").Append(_workspace);
        return true;
    }
}
