using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using OpenCode.Sdk.Tools.Generator.Binding;
using Testably.Abstractions;

namespace OpenCode.Sdk.Tools.Tests.Generator.Binding;

/// <summary>
/// Pins the reserved-name tables to the hand-written SDK surface they mirror, so a new public
/// spine type or response-spine member without a table entry fails here instead of emitting a
/// CS0101/CS0102 twin from a later batch. Hand-written files are recognized the same way the
/// compile probe recognizes them: generated sources carry the writer's header.
/// </summary>
public sealed class ReservedNamePolicyTests
{
    private const string GeneratedHeader = "// Generated by OpenCode.Sdk.Tools";

    /// <summary>The namespaces generated types are emitted into; a reserved twin there would not compile.</summary>
    private static readonly string[] GeneratedNamespaces = ["OpenCode.Sdk", "OpenCode.Sdk.Models"];

    [Test]
    public async Task SpineTypeNames_Should_Mirror_The_HandWritten_Public_Types_In_The_Generated_Namespaces()
    {
        var handWritten = new List<string>();
        foreach (var tree in await LoadHandWrittenSdkTreesAsync())
        {
            var root = await tree.GetRootAsync();
            handWritten.AddRange(root
                .DescendantNodes(static node => node is CompilationUnitSyntax or BaseNamespaceDeclarationSyntax)
                .OfType<MemberDeclarationSyntax>()
                .Where(static member => member is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax
                                     && member.Modifiers.Any(SyntaxKind.PublicKeyword)
                                     && GeneratedNamespaces.Contains(NamespaceOf(member), StringComparer.Ordinal))
                .Select(static member => member is DelegateDeclarationSyntax del
                    ? del.Identifier.ValueText
                    : ((BaseTypeDeclarationSyntax)member).Identifier.ValueText));
        }

        handWritten.Sort(StringComparer.Ordinal);
        await Assert.That(handWritten)
            .IsEquivalentTo(ReservedNamePolicy.SpineTypeNames.Order(StringComparer.Ordinal).ToArray());
    }

    [Test]
    public async Task PayloadNames_Should_Cover_Every_Public_Response_Spine_Member()
    {
        var spine = new List<string>();
        foreach (var tree in await LoadHandWrittenSdkTreesAsync())
        {
            var root = await tree.GetRootAsync();
            spine.AddRange(root
                .DescendantNodes()
                .OfType<TypeDeclarationSyntax>()
                .Where(static type => type.Identifier.ValueText == "OpenCodeResponse")
                .SelectMany(static type => type.Members)
                .Where(static member => member.Modifiers.Any(SyntaxKind.PublicKeyword))
                .Select(static member => member switch
                {
                    PropertyDeclarationSyntax property => property.Identifier.ValueText,
                    MethodDeclarationSyntax method => method.Identifier.ValueText,
                    _ => null,
                })
                .OfType<string>());
        }

        await Assert.That(spine).IsNotEmpty();
        var uncovered = spine
            .Where(static name => !ReservedNamePolicy.PayloadNames.Contains(name))
            .Order(StringComparer.Ordinal)
            .ToArray();
        await Assert.That(uncovered).IsEmpty();
    }

    private static string? NamespaceOf(MemberDeclarationSyntax member) =>
        member.Parent switch
        {
            BaseNamespaceDeclarationSyntax ns => ns.Name.ToString(),
            _ => null,
        };

    private static async Task<List<SyntaxTree>> LoadHandWrittenSdkTreesAsync()
    {
        var fileSystem = new RealFileSystem();
        var root = fileSystem.Path.Combine(AppContext.BaseDirectory, "Fixtures", "SdkSource");
        var trees = new List<SyntaxTree>();
        foreach (var path in fileSystem.Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
        {
            var text = await fileSystem.File.ReadAllTextAsync(path, CancellationToken.None);
            if (!text.StartsWith(GeneratedHeader, StringComparison.Ordinal))
            {
                trees.Add(CSharpSyntaxTree.ParseText(text, path: path));
            }
        }

        return trees;
    }
}
