// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/websearch&apos; operation.
/// </summary>
public sealed record WebsearchQueryPostResponse : OpenCodeResponse
{
    private readonly WebSearchResponse? _query;
    private readonly LocationInfo? _location;
    /// <summary>
    /// Initializes a success instance of the &apos;WebsearchQueryPostResponse&apos; envelope.
    /// </summary>
    public WebsearchQueryPostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal WebsearchQueryPostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Query = null!;
        Location = null!;
    }

    /// <summary>
    /// Gets the Query payload; guarded on the error path.
    /// </summary>
    public required WebSearchResponse Query { get => _query ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Query."); init => _query = value; }
    /// <summary>
    /// Gets the location the server resolved for the request; guarded on the error path.
    /// </summary>
    public required LocationInfo Location { get => _location ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Location."); init => _location = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_query is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Query = ").Append(_query);
        return true;
    }
}
