// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/experimental/session/{sessionID}/terminal&apos; operation.
/// </summary>
public sealed record PersistentPtyCreateResponse : OpenCodeResponse
{
    private readonly PersistentPtyInfo? _persistentPty;
    /// <summary>
    /// Initializes a success instance of the &apos;PersistentPtyCreateResponse&apos; envelope.
    /// </summary>
    public PersistentPtyCreateResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal PersistentPtyCreateResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        PersistentPty = null!;
    }

    /// <summary>
    /// Gets the PersistentPty payload; guarded on the error path.
    /// </summary>
    public required PersistentPtyInfo PersistentPty { get => _persistentPty ?? throw new InvalidOperationException("The response is an error; check IsError before accessing PersistentPty."); init => _persistentPty = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_persistentPty is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("PersistentPty = ").Append(_persistentPty);
        return true;
    }
}
