// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class ConfigInfoPluginsJsonConverter : JsonConverter<ConfigInfoPlugins>
{
    public override ConfigInfoPlugins Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        return reader.TokenType switch
        {
            JsonTokenType.String => ConfigInfoPlugins.FromText(reader.GetString() ?? throw new JsonException("The string arm materialized null.")),
            JsonTokenType.StartObject => ConfigInfoPlugins.FromConfigPluginEntry(ReadKnown<ConfigPluginEntry>(ref reader)),
            JsonTokenType.None => throw new JsonException("JSON token 'None' cannot start this structural union value."),
            JsonTokenType.EndObject => throw new JsonException("JSON token 'EndObject' cannot start this structural union value."),
            JsonTokenType.StartArray => ReadUnknown(ref reader),
            JsonTokenType.EndArray => throw new JsonException("JSON token 'EndArray' cannot start this structural union value."),
            JsonTokenType.PropertyName => throw new JsonException("JSON token 'PropertyName' cannot start this structural union value."),
            JsonTokenType.Comment => throw new JsonException("JSON token 'Comment' cannot start this structural union value."),
            JsonTokenType.Number => ReadUnknown(ref reader),
            JsonTokenType.True => ReadUnknown(ref reader),
            JsonTokenType.False => ReadUnknown(ref reader),
            JsonTokenType.Null => throw new JsonException("JSON token 'Null' cannot start this structural union value."),
            _ => throw new JsonException("The JSON token kind is not recognized.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ConfigInfoPlugins value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        switch (value.Kind)
        {
            case ConfigInfoPluginsKind.Text:
                writer.WriteStringValue(value.Text);
                break;
            case ConfigInfoPluginsKind.ConfigPluginEntry:
                WriteKnown(writer, value.ConfigPluginEntry);
                break;
            case ConfigInfoPluginsKind.Unknown:
                value.Unknown.WriteTo(writer);
                break;
            default:
                throw new JsonException("The structural union kind is not recognized.");
        }
    }

    private static T ReadKnown<T>(ref Utf8JsonReader reader)
        where T : notnull
    {
        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(typeof(T)) ?? throw new JsonException("The generated context has no structural union arm metadata.");
        var result = JsonSerializer.Deserialize(ref reader, typeInfo) ?? throw new JsonException("The structural union arm materialized null.");
        return (T)result;
    }

    private static void WriteKnown<T>(Utf8JsonWriter writer, T value)
        where T : notnull
    {
        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(typeof(T)) ?? throw new JsonException("The generated context has no structural union arm metadata.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }

    private static ConfigInfoPlugins ReadUnknown(ref Utf8JsonReader reader)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        return ConfigInfoPlugins.FromUnknown(document.RootElement);
    }
}
