// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;
/// <summary>
/// Carries the wire body of &apos;ExperimentalSessionInstructionsEntryListResponse&apos; through one deserialization pass.
/// </summary>
internal sealed record ExperimentalSessionInstructionsEntryListResponseEnvelope
{
    [JsonPropertyName("data")]
    public required IReadOnlyList<InstructionEntryInfo> Data { get; init; }
}
