// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class LlmToolContentJsonConverter : JsonConverter<LlmToolContent>
{
    private static readonly Dictionary<string, Type> TypesByTag = new(StringComparer.Ordinal)
    {
        ["file"] = typeof(ToolFileContent),
        ["text"] = typeof(ToolTextContent)
    };
    public override bool HandleNull => true;

    public override LlmToolContent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        if (reader.TokenType == JsonTokenType.Null)
        {
            throw new JsonException("The LlmToolContent payload cannot be null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        if (payload.ValueKind != JsonValueKind.Object)
        {
            throw new JsonException("The LlmToolContent payload must be a JSON object.");
        }

        if (!payload.TryGetProperty("type", out var markerElement))
        {
            throw new JsonException("The LlmToolContent payload must contain 'type'.");
        }

        if (markerElement.ValueKind != JsonValueKind.String)
        {
            throw new JsonException("The 'type' marker must be a string.");
        }

        var marker = markerElement.GetString() ?? throw new JsonException("The 'type' marker cannot be null.");
        if (TypesByTag.TryGetValue(marker, out var targetType))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for LlmToolContent.");
            return JsonSerializer.Deserialize(payload, typeInfo) as LlmToolContent ?? throw new JsonException("The LlmToolContent payload deserialized to null.");
        }

        return new UnknownLlmToolContent(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, LlmToolContent value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownLlmToolContent unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for LlmToolContent.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
