// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;
/// <summary>
/// Carries the wire body of &apos;MessageListResponse&apos; through one deserialization pass.
/// </summary>
internal sealed record MessageListResponseEnvelope
{
    [JsonPropertyName("data")]
    public required IReadOnlyList<SessionMessageInfo> Data { get; init; }

    [JsonPropertyName("cursor")]
    public required ListCursor Cursor { get; init; }
}
