// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class OpenCodeErrorJsonConverter : JsonConverter<OpenCodeError>
{
    private static readonly Dictionary<string, Type> TypesByTag = new(StringComparer.Ordinal)
    {
        ["InvalidCursorError"] = typeof(InvalidCursorError),
        ["InvalidRequestError"] = typeof(InvalidRequestError),
        ["MessageNotFoundError"] = typeof(MessageNotFoundError),
        ["SessionNotFoundError"] = typeof(SessionNotFoundError),
        ["ShellNotFoundError"] = typeof(ShellNotFoundError),
        ["UnauthorizedError"] = typeof(UnauthorizedError),
        ["UnknownError"] = typeof(UnknownError)
    };
    public override bool HandleNull => true;

    public override OpenCodeError Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        if (reader.TokenType == JsonTokenType.Null)
        {
            throw new JsonException("The OpenCodeError payload cannot be null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        if (payload.ValueKind != JsonValueKind.Object)
        {
            throw new JsonException("The OpenCodeError payload must be a JSON object.");
        }

        if (!payload.TryGetProperty("_tag", out var markerElement))
        {
            throw new JsonException("The OpenCodeError payload must contain '_tag'.");
        }

        if (markerElement.ValueKind != JsonValueKind.String)
        {
            throw new JsonException("The '_tag' marker must be a string.");
        }

        var marker = markerElement.GetString();
        if (marker is null || string.IsNullOrWhiteSpace(marker))
        {
            throw new JsonException("The '_tag' marker must be a non-empty string.");
        }

        if (TypesByTag.TryGetValue(marker, out var targetType))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for OpenCodeError.");
            return JsonSerializer.Deserialize(payload, typeInfo) as OpenCodeError ?? throw new JsonException("The OpenCodeError payload deserialized to null.");
        }

        return new UnknownOpenCodeError(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, OpenCodeError value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownOpenCodeError unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for OpenCodeError.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
