// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class PromptFileSourceJsonConverter : JsonConverter<IPromptFileSource>
{
    private static readonly Dictionary<string, Type> TypesByTag = new(StringComparer.Ordinal)
    {
        ["inline"] = typeof(PromptFileSourceInline),
        ["uri"] = typeof(PromptFileSourceUri)
    };
    private static readonly UnionDiscriminatorReader DiscriminatorReader = new();
    public override IPromptFileSource Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        var marker = DiscriminatorReader.ReadString(ref reader, "type", "PromptFileSource");
        if (TypesByTag.TryGetValue(marker, out var targetType))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for PromptFileSource.");
            return JsonSerializer.Deserialize(ref reader, typeInfo) as IPromptFileSource ?? throw new JsonException("The PromptFileSource payload deserialized to null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        return new UnknownPromptFileSource(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, IPromptFileSource value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownPromptFileSource unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for PromptFileSource.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
