// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class SessionMessageCompactionJsonConverter : JsonConverter<ISessionMessageCompaction>
{
    private static readonly Dictionary<string, Type> TypesByTag = new(StringComparer.Ordinal)
    {
        ["completed"] = typeof(SessionMessageCompactionCompleted),
        ["failed"] = typeof(SessionMessageCompactionFailed),
        ["running"] = typeof(SessionMessageCompactionRunning)
    };
    public override ISessionMessageCompaction Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        if (payload.ValueKind != JsonValueKind.Object)
        {
            throw new JsonException("The SessionMessageCompaction payload must be a JSON object.");
        }

        if (!payload.TryGetProperty("type", out var fixedElement))
        {
            throw new JsonException("The SessionMessageCompaction payload must contain 'type'.");
        }

        if (fixedElement.ValueKind != JsonValueKind.String || !fixedElement.ValueEquals("compaction"))
        {
            throw new JsonException("The 'type' marker must be 'compaction'.");
        }

        if (!payload.TryGetProperty("status", out var markerElement))
        {
            throw new JsonException("The SessionMessageCompaction payload must contain 'status'.");
        }

        if (markerElement.ValueKind != JsonValueKind.String)
        {
            throw new JsonException("The 'status' marker must be a string.");
        }

        var marker = markerElement.GetString();
        if (marker is null || string.IsNullOrWhiteSpace(marker))
        {
            throw new JsonException("The 'status' marker must be a non-empty string.");
        }

        if (TypesByTag.TryGetValue(marker, out var targetType))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for SessionMessageCompaction.");
            return JsonSerializer.Deserialize(payload, typeInfo) as ISessionMessageCompaction ?? throw new JsonException("The SessionMessageCompaction payload deserialized to null.");
        }

        return new UnknownSessionMessageCompaction(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, ISessionMessageCompaction value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownSessionMessageCompaction unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for SessionMessageCompaction.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
