// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class SessionEventDurableJsonConverter : JsonConverter<ISessionEventDurable>
{
    private static readonly FrozenDictionary<string, Type> TypesByTag = new Dictionary<string, Type>(StringComparer.Ordinal)
    {
        ["session.agent.selected"] = typeof(SessionAgentSelected),
        ["session.compaction.ended"] = typeof(SessionCompactionEnded),
        ["session.compaction.failed"] = typeof(SessionCompactionFailed),
        ["session.compaction.started"] = typeof(SessionCompactionStarted),
        ["session.created"] = typeof(SessionCreated),
        ["session.deleted"] = typeof(SessionDeleted),
        ["session.execution.failed"] = typeof(SessionExecutionFailed),
        ["session.execution.interrupted"] = typeof(SessionExecutionInterrupted),
        ["session.execution.started"] = typeof(SessionExecutionStarted),
        ["session.execution.succeeded"] = typeof(SessionExecutionSucceeded),
        ["session.forked"] = typeof(SessionForked),
        ["session.inbox.cancelled"] = typeof(SessionInboxCancelled),
        ["session.inbox.delivered"] = typeof(SessionInboxDelivered),
        ["session.inbox.delivery.changed"] = typeof(SessionInboxDeliveryChanged),
        ["session.inbox.enqueued"] = typeof(SessionInboxEnqueued),
        ["session.instructions.updated"] = typeof(SessionInstructionsUpdated),
        ["session.model.selected"] = typeof(SessionModelSelected),
        ["session.moved"] = typeof(SessionMoved),
        ["session.reasoning.ended"] = typeof(SessionReasoningEnded),
        ["session.reasoning.started"] = typeof(SessionReasoningStarted),
        ["session.renamed"] = typeof(SessionRenamed),
        ["session.retry.scheduled"] = typeof(SessionRetryScheduled),
        ["session.revert.cleared"] = typeof(SessionRevertCleared),
        ["session.revert.committed"] = typeof(SessionRevertCommitted),
        ["session.revert.staged"] = typeof(SessionRevertStaged),
        ["session.shell.ended"] = typeof(SessionShellEnded),
        ["session.shell.started"] = typeof(SessionShellStarted),
        ["session.skill.activated"] = typeof(SessionSkillActivated),
        ["session.step.ended"] = typeof(SessionStepEnded),
        ["session.step.failed"] = typeof(SessionStepFailed),
        ["session.step.started"] = typeof(SessionStepStarted),
        ["session.synthetic"] = typeof(SessionSynthetic),
        ["session.text.ended"] = typeof(SessionTextEnded),
        ["session.text.started"] = typeof(SessionTextStarted),
        ["session.tool.called"] = typeof(SessionToolCalled),
        ["session.tool.failed"] = typeof(SessionToolFailed),
        ["session.tool.input.ended"] = typeof(SessionToolInputEnded),
        ["session.tool.input.started"] = typeof(SessionToolInputStarted),
        ["session.tool.success"] = typeof(SessionToolSuccess),
        ["session.usage.recorded"] = typeof(SessionUsageRecorded)
    }.ToFrozenDictionary(StringComparer.Ordinal);
    private static readonly UnionDiscriminatorReader DiscriminatorReader = new();
    public override ISessionEventDurable Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        if (DiscriminatorReader.TryFindKnown(ref reader, "type", "SessionEventDurable", TypesByTag, out var targetType, out var marker))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for SessionEventDurable.");
            return JsonSerializer.Deserialize(ref reader, typeInfo) as ISessionEventDurable ?? throw new JsonException("The SessionEventDurable payload deserialized to null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        return new UnknownSessionEventDurable(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, ISessionEventDurable value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownSessionEventDurable unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for SessionEventDurable.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
