// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class SessionMessageAssistantContentJsonConverter : JsonConverter<ISessionMessageAssistantContent>
{
    private static readonly FrozenDictionary<string, Type> TypesByTag = new Dictionary<string, Type>(StringComparer.Ordinal)
    {
        ["reasoning"] = typeof(SessionMessageAssistantReasoning),
        ["text"] = typeof(SessionMessageAssistantText),
        ["tool"] = typeof(SessionMessageAssistantTool)
    }.ToFrozenDictionary(StringComparer.Ordinal);
    private static readonly UnionDiscriminatorReader DiscriminatorReader = new();
    public override ISessionMessageAssistantContent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        if (DiscriminatorReader.TryFindKnown(ref reader, "type", "SessionMessageAssistantContent", TypesByTag, out var targetType, out var marker))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for SessionMessageAssistantContent.");
            return JsonSerializer.Deserialize(ref reader, typeInfo) as ISessionMessageAssistantContent ?? throw new JsonException("The SessionMessageAssistantContent payload deserialized to null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        return new UnknownSessionMessageAssistantContent(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, ISessionMessageAssistantContent value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownSessionMessageAssistantContent unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for SessionMessageAssistantContent.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
