// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/session&apos; operation.
/// </summary>
public sealed record SessionListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<SessionInfo>? _sessions;
    private readonly ListCursor? _cursor;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionListResponse&apos; envelope.
    /// </summary>
    public SessionListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionListResponse(int status, OpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Sessions = null!;
        Cursor = null!;
    }

    /// <summary>
    /// Gets the Sessions payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<SessionInfo> Sessions { get => _sessions ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Sessions."); init => _sessions = value is null ? null : Array.AsReadOnly([.. value]); }
    /// <summary>
    /// Gets the page cursor; guarded on the error path.
    /// </summary>
    public required ListCursor Cursor { get => _cursor ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Cursor."); init => _cursor = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_sessions is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Sessions = ").Append(_sessions);
        return true;
    }
}
