// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/session/{sessionID}/instructions/entries&apos; operation.
/// </summary>
public sealed record SessionInstructionsEntryListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<InstructionEntryInfo>? _instructionsEntry;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionInstructionsEntryListResponse&apos; envelope.
    /// </summary>
    public SessionInstructionsEntryListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionInstructionsEntryListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        InstructionsEntry = null!;
    }

    /// <summary>
    /// Gets the InstructionsEntry payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<InstructionEntryInfo> InstructionsEntry { get => _instructionsEntry ?? throw new InvalidOperationException("The response is an error; check IsError before accessing InstructionsEntry."); init => _instructionsEntry = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_instructionsEntry is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("InstructionsEntry = ").Append(_instructionsEntry);
        return true;
    }
}
