// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/session/{sessionID}/form&apos; operation.
/// </summary>
public sealed record SessionFormCreateResponse : OpenCodeResponse
{
    private readonly FormInfo? _form;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionFormCreateResponse&apos; envelope.
    /// </summary>
    public SessionFormCreateResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionFormCreateResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Form = null!;
    }

    /// <summary>
    /// Gets the Form payload; guarded on the error path.
    /// </summary>
    public required FormInfo Form { get => _form ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Form."); init => _form = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_form is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Form = ").Append(_form);
        return true;
    }
}
