// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;GET /api/session&apos; query. &apos;limit&apos;: Maximum number of sessions to return. Defaults to the newest 50 sessions. &apos;order&apos;: Session order for the first page. Use desc for newest first or asc for oldest first. &apos;cursor&apos;: Opaque pagination cursor returned as cursor.previous or cursor.next in the previous response.
/// </summary>
public sealed record SessionListRequest : ListRequest
{
    /// <summary>
    /// Gets the &apos;workspace&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Workspace { get; init; }
    /// <summary>
    /// Gets the &apos;search&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Search { get; init; }
    /// <summary>
    /// Filter by parent session. Use null to return only root sessions.
    /// </summary>
    public SessionParentFilter? ParentId { get; init; }
    /// <summary>
    /// Gets the &apos;directory&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Directory { get; init; }
    /// <summary>
    /// Gets the &apos;project&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Project { get; init; }
    /// <summary>
    /// Gets the &apos;subpath&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Subpath { get; init; }
}
