// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/session/{sessionID}/message/{messageID}&apos; operation.
/// </summary>
public sealed record SessionMessageResponse : OpenCodeResponse
{
    private readonly ISessionMessageInfo? _message;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionMessageResponse&apos; envelope.
    /// </summary>
    public SessionMessageResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionMessageResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Message = null!;
    }

    /// <summary>
    /// Gets the Message payload; guarded on the error path.
    /// </summary>
    public required ISessionMessageInfo Message { get => _message ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Message."); init => _message = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_message is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Message = ").Append(_message);
        return true;
    }
}
