// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/session/{sessionID}&apos; operation.
/// </summary>
public sealed record SessionResponse : OpenCodeResponse
{
    private readonly SessionInfo? _session;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionResponse&apos; envelope.
    /// </summary>
    public SessionResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionResponse(int status, OpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Session = null!;
    }

    /// <summary>
    /// Gets the Session payload; guarded on the error path.
    /// </summary>
    public required SessionInfo Session { get => _session ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Session."); init => _session = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_session is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Session = ").Append(_session);
        return true;
    }
}
