// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/session/import&apos; operation.
/// </summary>
public sealed record SessionImportPostResponse : OpenCodeResponse
{
    private readonly SessionInfo? _import;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionImportPostResponse&apos; envelope.
    /// </summary>
    public SessionImportPostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionImportPostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Import = null!;
    }

    /// <summary>
    /// Gets the Import payload; guarded on the error path.
    /// </summary>
    public required SessionInfo Import { get => _import ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Import."); init => _import = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_import is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Import = ").Append(_import);
        return true;
    }
}
