// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/session/{sessionID}/generate&apos; operation.
/// </summary>
public sealed record SessionGeneratePostResponse : OpenCodeResponse
{
    private readonly SessionGeneratePostData? _generate;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionGeneratePostResponse&apos; envelope.
    /// </summary>
    public SessionGeneratePostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionGeneratePostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Generate = null!;
    }

    /// <summary>
    /// Gets the Generate payload; guarded on the error path.
    /// </summary>
    public required SessionGeneratePostData Generate { get => _generate ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Generate."); init => _generate = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_generate is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Generate = ").Append(_generate);
        return true;
    }
}
