// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;POST /api/session/{sessionID}/interrupt&apos; query.
/// </summary>
public sealed record SessionInterruptPostRequest
{
    /// <summary>
    /// Gets the &apos;resume&apos; query value; the server default applies when unset.
    /// </summary>
    public QueryBoolean? Resume { get; init; }
}
