// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Internal.StreamAdapters;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// A bound &apos;SessionClient&apos; handle; it holds an immutable identifier and the shared pipeline.
/// </summary>
public class SessionClient
{
    private readonly Pipeline? _pipeline;
    private readonly string? _sessionId;
    internal SessionClient(Pipeline pipeline, string sessionId)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
        if (sessionId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
        }

        _pipeline = pipeline;
        _sessionId = sessionId;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected SessionClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("SessionClient", "Pipeline");
    private string SessionId => _sessionId ?? throw MockSeam.CreateError("SessionClient", "SessionId");

    /// <summary>
    /// Read the session log
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ISessionLogItem&apos; stream.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned a declared error status (declared: 400, 401, 404); streaming API errors always throw.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached, the stream failed after it opened, or a frame was malformed.</exception>
    public virtual IAsyncEnumerable<ISessionLogItem> GetLogAsync(SessionLogRequest? request = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteStreamAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetLog(SessionId, request), SessionLogResponseStreamAdapter.Instance, cancellationToken);
    }

    /// <summary>
    /// Get session message
    /// </summary>
    /// <param name = "messageId">The &apos;messageID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionMessageResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<SessionMessageResponse> GetMessageAsync(string messageId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(messageId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetMessage(SessionId, messageId), SessionMessageResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<SessionResponse> GetSessionAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetSession(SessionId), SessionResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session messages
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;MessageListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<MessageListResponse> ListMessagesAsync(MessageListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.ListMessages(SessionId, request), MessageListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Delete session
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<SessionRemoveResponse> RemoveSessionAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Sessions.RemoveSession(SessionId), SessionRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Rename session
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionRenameResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<SessionRenameResponse> RenameSessionAsync(SessionRenameRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.RenameSession(SessionId), request, OpenCodeJsonContext.Default.SessionRenameRequest, SessionRenameResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
