// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/session/{sessionID}/synthetic&apos; operation.
/// </summary>
public sealed record SessionSyntheticPostResponse : OpenCodeResponse
{
    private readonly SessionInboxSynthetic? _synthetic;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionSyntheticPostResponse&apos; envelope.
    /// </summary>
    public SessionSyntheticPostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionSyntheticPostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Synthetic = null!;
    }

    /// <summary>
    /// Gets the Synthetic payload; guarded on the error path.
    /// </summary>
    public required SessionInboxSynthetic Synthetic { get => _synthetic ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Synthetic."); init => _synthetic = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_synthetic is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Synthetic = ").Append(_synthetic);
        return true;
    }
}
