// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/session/{sessionID}/interrupt&apos; operation.
/// </summary>
public sealed record SessionInterruptPostResponse : OpenCodeResponse
{
    private readonly SessionInterruptResponse? _interrupt;
    /// <summary>
    /// Initializes a success instance of the &apos;SessionInterruptPostResponse&apos; envelope.
    /// </summary>
    public SessionInterruptPostResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal SessionInterruptPostResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Interrupt = null!;
    }

    /// <summary>
    /// Gets the Interrupt payload; guarded on the error path.
    /// </summary>
    public required SessionInterruptResponse Interrupt { get => _interrupt ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Interrupt."); init => _interrupt = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_interrupt is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Interrupt = ").Append(_interrupt);
        return true;
    }
}
