// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;GET /api/session/{sessionID}/message&apos; query.
/// </summary>
public sealed record MessageListRequest : ListRequest
{
}
