// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Defines the wire route of every generated operation.
/// </summary>
public static class OpenCodeRoutes
{
    /// <summary>
    /// Defines the &apos;Agents&apos; routes.
    /// </summary>
    public static class Agents
    {
        /// <summary>
        /// The &apos;GET /api/agent/{agentID}&apos; route template.
        /// </summary>
        public const string GetAgentTemplate = "/api/agent/{agentID}";
        /// <summary>
        /// Builds the &apos;/api/agent/{agentID}&apos; route.
        /// </summary>
        /// <param name = "agentId">The &apos;agentID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetAgent(string agentId, AgentRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(agentId);
            if (agentId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(agentId));
            }

            var path = "/api/agent/" + RouteValuePolicy.Escape(agentId, nameof(agentId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/agent&apos; route template.
        /// </summary>
        public const string ListAgentsTemplate = "/api/agent";
        /// <summary>
        /// Builds the &apos;/api/agent&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListAgents(AgentListRequest? request = null)
        {
            var path = "/api/agent";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Commands&apos; routes.
    /// </summary>
    public static class Commands
    {
        /// <summary>
        /// The &apos;GET /api/command&apos; route template.
        /// </summary>
        public const string ListCommandsTemplate = "/api/command";
        /// <summary>
        /// Builds the &apos;/api/command&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListCommands(CommandListRequest? request = null)
        {
            var path = "/api/command";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Credentials&apos; routes.
    /// </summary>
    public static class Credentials
    {
        /// <summary>
        /// The &apos;DELETE /api/credential/{credentialID}&apos; route template.
        /// </summary>
        public const string RemoveCredentialTemplate = "/api/credential/{credentialID}";
        /// <summary>
        /// Builds the &apos;/api/credential/{credentialID}&apos; route.
        /// </summary>
        /// <param name = "credentialId">The &apos;credentialID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveCredential(string credentialId, CredentialRemoveRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(credentialId);
            if (credentialId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(credentialId));
            }

            var path = "/api/credential/" + RouteValuePolicy.Escape(credentialId, nameof(credentialId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;PATCH /api/credential/{credentialID}&apos; route template.
        /// </summary>
        public const string UpdateCredentialTemplate = "/api/credential/{credentialID}";
        /// <summary>
        /// Builds the &apos;/api/credential/{credentialID}&apos; route.
        /// </summary>
        /// <param name = "credentialId">The &apos;credentialID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string UpdateCredential(string credentialId, CredentialUpdatePatchRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(credentialId);
            if (credentialId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(credentialId));
            }

            var path = "/api/credential/" + RouteValuePolicy.Escape(credentialId, nameof(credentialId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Debug&apos; routes.
    /// </summary>
    public static class Debug
    {
        /// <summary>
        /// The &apos;DELETE /api/debug/location&apos; route template.
        /// </summary>
        public const string EvictLocationTemplate = "/api/debug/location";
        /// <summary>
        /// Builds the &apos;/api/debug/location&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string EvictLocation(DebugLocationEvictDeleteRequest? request = null)
        {
            var path = "/api/debug/location";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Events&apos; routes.
    /// </summary>
    public static class Events
    {
        /// <summary>
        /// The &apos;GET /api/event&apos; route.
        /// </summary>
        public const string Subscribe = "/api/event";
    }

    /// <summary>
    /// Defines the &apos;Experimental&apos; routes.
    /// </summary>
    public static class Experimental
    {
        /// <summary>
        /// The &apos;POST /api/experimental/integration/wellknown&apos; route template.
        /// </summary>
        public const string AddIntegrationWellknownTemplate = "/api/experimental/integration/wellknown";
        /// <summary>
        /// Builds the &apos;/api/experimental/integration/wellknown&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string AddIntegrationWellknown(ExperimentalIntegrationWellknownAddPostRequest? request = null)
        {
            var path = "/api/experimental/integration/wellknown";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Generation&apos; routes.
    /// </summary>
    public static class Generation
    {
        /// <summary>
        /// The &apos;POST /api/generate&apos; route.
        /// </summary>
        public const string GenerateText = "/api/generate";
    }

    /// <summary>
    /// Defines the &apos;Health&apos; routes.
    /// </summary>
    public static class Health
    {
        /// <summary>
        /// The &apos;GET /api/health&apos; route.
        /// </summary>
        public const string Get = "/api/health";
    }

    /// <summary>
    /// Defines the &apos;Integrations&apos; routes.
    /// </summary>
    public static class Integrations
    {
        /// <summary>
        /// The &apos;DELETE /api/integration/{integrationID}/connect/command/{attemptID}&apos; route template.
        /// </summary>
        public const string DeleteCommandCancelTemplate = "/api/integration/{integrationID}/connect/command/{attemptID}";
        /// <summary>
        /// Builds the &apos;/api/integration/{integrationID}/connect/command/{attemptID}&apos; route.
        /// </summary>
        /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
        /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string DeleteCommandCancel(string integrationId, string attemptId, IntegrationCommandCancelDeleteRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
            if (integrationId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(attemptId);
            if (attemptId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(attemptId));
            }

            var path = "/api/integration/" + RouteValuePolicy.Escape(integrationId, nameof(integrationId)) + "/connect/command/" + RouteValuePolicy.Escape(attemptId, nameof(attemptId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/integration/{integrationID}/connect/oauth/{attemptID}&apos; route template.
        /// </summary>
        public const string DeleteOauthCancelTemplate = "/api/integration/{integrationID}/connect/oauth/{attemptID}";
        /// <summary>
        /// Builds the &apos;/api/integration/{integrationID}/connect/oauth/{attemptID}&apos; route.
        /// </summary>
        /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
        /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string DeleteOauthCancel(string integrationId, string attemptId, IntegrationOauthCancelDeleteRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
            if (integrationId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(attemptId);
            if (attemptId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(attemptId));
            }

            var path = "/api/integration/" + RouteValuePolicy.Escape(integrationId, nameof(integrationId)) + "/connect/oauth/" + RouteValuePolicy.Escape(attemptId, nameof(attemptId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/integration/{integrationID}/connect/command/{attemptID}&apos; route template.
        /// </summary>
        public const string GetCommandStatusTemplate = "/api/integration/{integrationID}/connect/command/{attemptID}";
        /// <summary>
        /// Builds the &apos;/api/integration/{integrationID}/connect/command/{attemptID}&apos; route.
        /// </summary>
        /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
        /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetCommandStatus(string integrationId, string attemptId, IntegrationCommandStatusRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
            if (integrationId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(attemptId);
            if (attemptId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(attemptId));
            }

            var path = "/api/integration/" + RouteValuePolicy.Escape(integrationId, nameof(integrationId)) + "/connect/command/" + RouteValuePolicy.Escape(attemptId, nameof(attemptId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/integration/{integrationID}/connect/oauth/{attemptID}&apos; route template.
        /// </summary>
        public const string GetOauthStatusTemplate = "/api/integration/{integrationID}/connect/oauth/{attemptID}";
        /// <summary>
        /// Builds the &apos;/api/integration/{integrationID}/connect/oauth/{attemptID}&apos; route.
        /// </summary>
        /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
        /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetOauthStatus(string integrationId, string attemptId, IntegrationOauthStatusRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
            if (integrationId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(attemptId);
            if (attemptId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(attemptId));
            }

            var path = "/api/integration/" + RouteValuePolicy.Escape(integrationId, nameof(integrationId)) + "/connect/oauth/" + RouteValuePolicy.Escape(attemptId, nameof(attemptId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/integration/{integrationID}/connect/command&apos; route template.
        /// </summary>
        public const string PostCommandConnectTemplate = "/api/integration/{integrationID}/connect/command";
        /// <summary>
        /// Builds the &apos;/api/integration/{integrationID}/connect/command&apos; route.
        /// </summary>
        /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PostCommandConnect(string integrationId, IntegrationCommandConnectPostRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
            if (integrationId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
            }

            var path = "/api/integration/" + RouteValuePolicy.Escape(integrationId, nameof(integrationId)) + "/connect/command";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/integration/{integrationID}/connect/oauth/{attemptID}/complete&apos; route template.
        /// </summary>
        public const string PostOauthCompleteTemplate = "/api/integration/{integrationID}/connect/oauth/{attemptID}/complete";
        /// <summary>
        /// Builds the &apos;/api/integration/{integrationID}/connect/oauth/{attemptID}/complete&apos; route.
        /// </summary>
        /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
        /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PostOauthComplete(string integrationId, string attemptId, IntegrationOauthCompletePostRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
            if (integrationId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(attemptId);
            if (attemptId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(attemptId));
            }

            var path = "/api/integration/" + RouteValuePolicy.Escape(integrationId, nameof(integrationId)) + "/connect/oauth/" + RouteValuePolicy.Escape(attemptId, nameof(attemptId)) + "/complete";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;LanguageModels&apos; routes.
    /// </summary>
    public static class LanguageModels
    {
        /// <summary>
        /// The &apos;GET /api/model&apos; route template.
        /// </summary>
        public const string ListModelsTemplate = "/api/model";
        /// <summary>
        /// Builds the &apos;/api/model&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListModels(ModelListRequest? request = null)
        {
            var path = "/api/model";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;McpServers&apos; routes.
    /// </summary>
    public static class McpServers
    {
        /// <summary>
        /// The &apos;GET /api/mcp/resource&apos; route template.
        /// </summary>
        public const string GetResourceCatalogTemplate = "/api/mcp/resource";
        /// <summary>
        /// Builds the &apos;/api/mcp/resource&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetResourceCatalog(McpResourceCatalogRequest? request = null)
        {
            var path = "/api/mcp/resource";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/mcp&apos; route template.
        /// </summary>
        public const string ListMcpServersTemplate = "/api/mcp";
        /// <summary>
        /// Builds the &apos;/api/mcp&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListMcpServers(McpListRequest? request = null)
        {
            var path = "/api/mcp";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/mcp/{server}/connect&apos; route template.
        /// </summary>
        public const string PostConnectTemplate = "/api/mcp/{server}/connect";
        /// <summary>
        /// Builds the &apos;/api/mcp/{server}/connect&apos; route.
        /// </summary>
        /// <param name = "server">The &apos;server&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PostConnect(string server, McpConnectPostRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(server);
            if (server is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(server));
            }

            var path = "/api/mcp/" + RouteValuePolicy.Escape(server, nameof(server)) + "/connect";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/mcp/{server}/disconnect&apos; route template.
        /// </summary>
        public const string PostDisconnectTemplate = "/api/mcp/{server}/disconnect";
        /// <summary>
        /// Builds the &apos;/api/mcp/{server}/disconnect&apos; route.
        /// </summary>
        /// <param name = "server">The &apos;server&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PostDisconnect(string server, McpDisconnectPostRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(server);
            if (server is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(server));
            }

            var path = "/api/mcp/" + RouteValuePolicy.Escape(server, nameof(server)) + "/disconnect";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;PUT /api/mcp/{server}&apos; route template.
        /// </summary>
        public const string PutAddTemplate = "/api/mcp/{server}";
        /// <summary>
        /// Builds the &apos;/api/mcp/{server}&apos; route.
        /// </summary>
        /// <param name = "server">The &apos;server&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PutAdd(string server, McpAddPutRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(server);
            if (server is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(server));
            }

            var path = "/api/mcp/" + RouteValuePolicy.Escape(server, nameof(server));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/mcp/{server}&apos; route template.
        /// </summary>
        public const string RemoveMcpServerTemplate = "/api/mcp/{server}";
        /// <summary>
        /// Builds the &apos;/api/mcp/{server}&apos; route.
        /// </summary>
        /// <param name = "server">The &apos;server&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveMcpServer(string server, McpRemoveRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(server);
            if (server is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(server));
            }

            var path = "/api/mcp/" + RouteValuePolicy.Escape(server, nameof(server));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Permissions&apos; routes.
    /// </summary>
    public static class Permissions
    {
        /// <summary>
        /// The &apos;GET /api/permission/request&apos; route template.
        /// </summary>
        public const string ListRequestsTemplate = "/api/permission/request";
        /// <summary>
        /// Builds the &apos;/api/permission/request&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListRequests(PermissionRequestListRequest? request = null)
        {
            var path = "/api/permission/request";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/permission/saved/{id}&apos; route template.
        /// </summary>
        public const string RemoveSavedTemplate = "/api/permission/saved/{id}";
        /// <summary>
        /// Builds the &apos;/api/permission/saved/{id}&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveSaved(string id)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            return "/api/permission/saved/" + RouteValuePolicy.Escape(id, nameof(id));
        }
    }

    /// <summary>
    /// Defines the &apos;Plugins&apos; routes.
    /// </summary>
    public static class Plugins
    {
        /// <summary>
        /// The &apos;GET /api/plugin&apos; route template.
        /// </summary>
        public const string ListPluginsTemplate = "/api/plugin";
        /// <summary>
        /// Builds the &apos;/api/plugin&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListPlugins(PluginListRequest? request = null)
        {
            var path = "/api/plugin";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Projects&apos; routes.
    /// </summary>
    public static class Projects
    {
        /// <summary>
        /// The &apos;GET /api/project/current&apos; route template.
        /// </summary>
        public const string GetCurrentTemplate = "/api/project/current";
        /// <summary>
        /// Builds the &apos;/api/project/current&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetCurrent(ProjectCurrentRequest? request = null)
        {
            var path = "/api/project/current";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Providers&apos; routes.
    /// </summary>
    public static class Providers
    {
        /// <summary>
        /// The &apos;GET /api/provider/{providerID}&apos; route template.
        /// </summary>
        public const string GetProviderTemplate = "/api/provider/{providerID}";
        /// <summary>
        /// Builds the &apos;/api/provider/{providerID}&apos; route.
        /// </summary>
        /// <param name = "providerId">The &apos;providerID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetProvider(string providerId, ProviderRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(providerId);
            if (providerId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(providerId));
            }

            var path = "/api/provider/" + RouteValuePolicy.Escape(providerId, nameof(providerId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/provider&apos; route template.
        /// </summary>
        public const string ListProvidersTemplate = "/api/provider";
        /// <summary>
        /// Builds the &apos;/api/provider&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListProviders(ProviderListRequest? request = null)
        {
            var path = "/api/provider";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Ptys&apos; routes.
    /// </summary>
    public static class Ptys
    {
        /// <summary>
        /// The &apos;POST /api/pty&apos; route template.
        /// </summary>
        public const string CreatePtyTemplate = "/api/pty";
        /// <summary>
        /// Builds the &apos;/api/pty&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string CreatePty(PtyCreateRequest? request = null)
        {
            var path = "/api/pty";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/pty/{ptyID}&apos; route template.
        /// </summary>
        public const string GetPtyTemplate = "/api/pty/{ptyID}";
        /// <summary>
        /// Builds the &apos;/api/pty/{ptyID}&apos; route.
        /// </summary>
        /// <param name = "ptyId">The &apos;ptyID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetPty(string ptyId, PtyRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(ptyId);
            if (ptyId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(ptyId));
            }

            var path = "/api/pty/" + RouteValuePolicy.Escape(ptyId, nameof(ptyId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;PUT /api/pty/{ptyID}&apos; route template.
        /// </summary>
        public const string PutUpdateTemplate = "/api/pty/{ptyID}";
        /// <summary>
        /// Builds the &apos;/api/pty/{ptyID}&apos; route.
        /// </summary>
        /// <param name = "ptyId">The &apos;ptyID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PutUpdate(string ptyId, PtyUpdatePutRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(ptyId);
            if (ptyId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(ptyId));
            }

            var path = "/api/pty/" + RouteValuePolicy.Escape(ptyId, nameof(ptyId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/pty/{ptyID}&apos; route template.
        /// </summary>
        public const string RemovePtyTemplate = "/api/pty/{ptyID}";
        /// <summary>
        /// Builds the &apos;/api/pty/{ptyID}&apos; route.
        /// </summary>
        /// <param name = "ptyId">The &apos;ptyID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string RemovePty(string ptyId, PtyRemoveRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(ptyId);
            if (ptyId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(ptyId));
            }

            var path = "/api/pty/" + RouteValuePolicy.Escape(ptyId, nameof(ptyId));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;References&apos; routes.
    /// </summary>
    public static class References
    {
        /// <summary>
        /// The &apos;GET /api/reference&apos; route template.
        /// </summary>
        public const string ListReferencesTemplate = "/api/reference";
        /// <summary>
        /// Builds the &apos;/api/reference&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListReferences(ReferenceListRequest? request = null)
        {
            var path = "/api/reference";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Sessions&apos; routes.
    /// </summary>
    public static class Sessions
    {
        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/permission&apos; route template.
        /// </summary>
        public const string CreatePermissionTemplate = "/api/session/{sessionID}/permission";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/permission&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string CreatePermission(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/permission";
        }

        /// <summary>
        /// The &apos;POST /api/session&apos; route.
        /// </summary>
        public const string CreateSession = "/api/session";
        /// <summary>
        /// The &apos;DELETE /api/session/{sessionID}/inbox/{inboxID}&apos; route template.
        /// </summary>
        public const string DeleteInboxCancelTemplate = "/api/session/{sessionID}/inbox/{inboxID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/inbox/{inboxID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "inboxId">The &apos;inboxID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string DeleteInboxCancel(string sessionId, string inboxId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(inboxId);
            if (inboxId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(inboxId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/inbox/" + RouteValuePolicy.Escape(inboxId, nameof(inboxId));
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/export&apos; route template.
        /// </summary>
        public const string GetExportTemplate = "/api/session/{sessionID}/export";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/export&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetExport(string sessionId, SessionExportRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            var path = "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/export";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddBoolean("sanitize", request.Sanitize);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/experimental/session/{sessionID}/log&apos; route template.
        /// </summary>
        public const string GetLogTemplate = "/api/experimental/session/{sessionID}/log";
        /// <summary>
        /// Builds the &apos;/api/experimental/session/{sessionID}/log&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetLog(string sessionId, SessionLogRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            var path = "/api/experimental/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/log";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddText("after", request.After);
            query.AddBoolean("follow", request.Follow);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/message/{messageID}&apos; route template.
        /// </summary>
        public const string GetMessageTemplate = "/api/session/{sessionID}/message/{messageID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/message/{messageID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "messageId">The &apos;messageID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string GetMessage(string sessionId, string messageId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(messageId);
            if (messageId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(messageId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/message/" + RouteValuePolicy.Escape(messageId, nameof(messageId));
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/permission/{requestID}&apos; route template.
        /// </summary>
        public const string GetPermissionTemplate = "/api/session/{sessionID}/permission/{requestID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/permission/{requestID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "requestId">The &apos;requestID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string GetPermission(string sessionId, string requestId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(requestId);
            if (requestId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(requestId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/permission/" + RouteValuePolicy.Escape(requestId, nameof(requestId));
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}&apos; route template.
        /// </summary>
        public const string GetSessionTemplate = "/api/session/{sessionID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string GetSession(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId));
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/message&apos; route template.
        /// </summary>
        public const string ListMessagesTemplate = "/api/session/{sessionID}/message";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/message&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListMessages(string sessionId, MessageListRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            var path = "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/message";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddText("limit", request.Limit);
            query.AddOrder("order", request.Order);
            query.AddText("cursor", request.Cursor);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/session&apos; route template.
        /// </summary>
        public const string ListSessionsTemplate = "/api/session";
        /// <summary>
        /// Builds the &apos;/api/session&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListSessions(SessionListRequest? request = null)
        {
            var path = "/api/session";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddText("workspace", request.Workspace);
            query.AddText("limit", request.Limit);
            query.AddOrder("order", request.Order);
            query.AddText("search", request.Search);
            query.AddParentFilter("parentID", request.ParentId);
            query.AddText("directory", request.Directory);
            query.AddText("project", request.Project);
            query.AddText("subpath", request.Subpath);
            query.AddText("cursor", request.Cursor);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/background&apos; route template.
        /// </summary>
        public const string PostBackgroundTemplate = "/api/session/{sessionID}/background";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/background&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostBackground(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/background";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/command&apos; route template.
        /// </summary>
        public const string PostCommandTemplate = "/api/session/{sessionID}/command";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/command&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostCommand(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/command";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/compact&apos; route template.
        /// </summary>
        public const string PostCompactTemplate = "/api/session/{sessionID}/compact";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/compact&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostCompact(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/compact";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/fork&apos; route template.
        /// </summary>
        public const string PostForkTemplate = "/api/session/{sessionID}/fork";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/fork&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostFork(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/fork";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/form/{formID}/cancel&apos; route template.
        /// </summary>
        public const string PostFormCancelTemplate = "/api/session/{sessionID}/form/{formID}/cancel";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/form/{formID}/cancel&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "formId">The &apos;formID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostFormCancel(string sessionId, string formId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(formId);
            if (formId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(formId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/form/" + RouteValuePolicy.Escape(formId, nameof(formId)) + "/cancel";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/generate&apos; route template.
        /// </summary>
        public const string PostGenerateTemplate = "/api/session/{sessionID}/generate";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/generate&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostGenerate(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/generate";
        }

        /// <summary>
        /// The &apos;POST /api/session/import&apos; route.
        /// </summary>
        public const string PostImport = "/api/session/import";
        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/inbox/{inboxID}/queue&apos; route template.
        /// </summary>
        public const string PostInboxQueueTemplate = "/api/session/{sessionID}/inbox/{inboxID}/queue";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/inbox/{inboxID}/queue&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "inboxId">The &apos;inboxID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostInboxQueue(string sessionId, string inboxId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(inboxId);
            if (inboxId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(inboxId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/inbox/" + RouteValuePolicy.Escape(inboxId, nameof(inboxId)) + "/queue";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/inbox/{inboxID}/steer&apos; route template.
        /// </summary>
        public const string PostInboxSteerTemplate = "/api/session/{sessionID}/inbox/{inboxID}/steer";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/inbox/{inboxID}/steer&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "inboxId">The &apos;inboxID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostInboxSteer(string sessionId, string inboxId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(inboxId);
            if (inboxId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(inboxId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/inbox/" + RouteValuePolicy.Escape(inboxId, nameof(inboxId)) + "/steer";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/interrupt&apos; route template.
        /// </summary>
        public const string PostInterruptTemplate = "/api/session/{sessionID}/interrupt";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/interrupt&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string PostInterrupt(string sessionId, SessionInterruptPostRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            var path = "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/interrupt";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddBoolean("continue", request.Continue);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/move&apos; route template.
        /// </summary>
        public const string PostMoveTemplate = "/api/session/{sessionID}/move";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/move&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostMove(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/move";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/permission/{requestID}/reply&apos; route template.
        /// </summary>
        public const string PostPermissionReplyTemplate = "/api/session/{sessionID}/permission/{requestID}/reply";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/permission/{requestID}/reply&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "requestId">The &apos;requestID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostPermissionReply(string sessionId, string requestId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(requestId);
            if (requestId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(requestId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/permission/" + RouteValuePolicy.Escape(requestId, nameof(requestId)) + "/reply";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/prompt&apos; route template.
        /// </summary>
        public const string PostPromptTemplate = "/api/session/{sessionID}/prompt";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/prompt&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostPrompt(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/prompt";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/revert/clear&apos; route template.
        /// </summary>
        public const string PostRevertClearTemplate = "/api/session/{sessionID}/revert/clear";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/revert/clear&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostRevertClear(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/revert/clear";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/revert/commit&apos; route template.
        /// </summary>
        public const string PostRevertCommitTemplate = "/api/session/{sessionID}/revert/commit";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/revert/commit&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostRevertCommit(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/revert/commit";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/revert/stage&apos; route template.
        /// </summary>
        public const string PostRevertStageTemplate = "/api/session/{sessionID}/revert/stage";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/revert/stage&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostRevertStage(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/revert/stage";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/shell&apos; route template.
        /// </summary>
        public const string PostShellTemplate = "/api/session/{sessionID}/shell";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/shell&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostShell(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/shell";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/skill&apos; route template.
        /// </summary>
        public const string PostSkillTemplate = "/api/session/{sessionID}/skill";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/skill&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostSkill(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/skill";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/agent&apos; route template.
        /// </summary>
        public const string PostSwitchAgentTemplate = "/api/session/{sessionID}/agent";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/agent&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostSwitchAgent(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/agent";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/model&apos; route template.
        /// </summary>
        public const string PostSwitchModelTemplate = "/api/session/{sessionID}/model";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/model&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostSwitchModel(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/model";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/synthetic&apos; route template.
        /// </summary>
        public const string PostSyntheticTemplate = "/api/session/{sessionID}/synthetic";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/synthetic&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostSynthetic(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/synthetic";
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/wait&apos; route template.
        /// </summary>
        public const string PostWaitTemplate = "/api/session/{sessionID}/wait";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/wait&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PostWait(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/wait";
        }

        /// <summary>
        /// The &apos;PUT /api/session/{sessionID}/instructions/entries/{key}&apos; route template.
        /// </summary>
        public const string PutInstructionsEntryTemplate = "/api/session/{sessionID}/instructions/entries/{key}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/instructions/entries/{key}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "key">The &apos;key&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string PutInstructionsEntry(string sessionId, string key)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(key);
            if (key is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(key));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/instructions/entries/" + RouteValuePolicy.Escape(key, nameof(key));
        }

        /// <summary>
        /// The &apos;DELETE /api/session/{sessionID}/instructions/entries/{key}&apos; route template.
        /// </summary>
        public const string RemoveInstructionsEntryTemplate = "/api/session/{sessionID}/instructions/entries/{key}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/instructions/entries/{key}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "key">The &apos;key&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveInstructionsEntry(string sessionId, string key)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(key);
            if (key is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(key));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/instructions/entries/" + RouteValuePolicy.Escape(key, nameof(key));
        }

        /// <summary>
        /// The &apos;DELETE /api/session/{sessionID}&apos; route template.
        /// </summary>
        public const string RemoveSessionTemplate = "/api/session/{sessionID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveSession(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId));
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/rename&apos; route template.
        /// </summary>
        public const string RenameSessionTemplate = "/api/session/{sessionID}/rename";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/rename&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string RenameSession(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + RouteValuePolicy.Escape(sessionId, nameof(sessionId)) + "/rename";
        }
    }

    /// <summary>
    /// Defines the &apos;Shells&apos; routes.
    /// </summary>
    public static class Shells
    {
        /// <summary>
        /// The &apos;POST /api/shell&apos; route template.
        /// </summary>
        public const string CreateShellTemplate = "/api/shell";
        /// <summary>
        /// Builds the &apos;/api/shell&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string CreateShell(ShellCreateRequest? request = null)
        {
            var path = "/api/shell";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/shell/{id}&apos; route template.
        /// </summary>
        public const string GetShellTemplate = "/api/shell/{id}";
        /// <summary>
        /// Builds the &apos;/api/shell/{id}&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetShell(string id, ShellRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            var path = "/api/shell/" + RouteValuePolicy.Escape(id, nameof(id));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/shell&apos; route template.
        /// </summary>
        public const string ListShellsTemplate = "/api/shell";
        /// <summary>
        /// Builds the &apos;/api/shell&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListShells(ShellListRequest? request = null)
        {
            var path = "/api/shell";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/shell/{id}&apos; route template.
        /// </summary>
        public const string RemoveShellTemplate = "/api/shell/{id}";
        /// <summary>
        /// Builds the &apos;/api/shell/{id}&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveShell(string id, ShellRemoveRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            var path = "/api/shell/" + RouteValuePolicy.Escape(id, nameof(id));
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;PATCH /api/shell/{id}/timeout&apos; route template.
        /// </summary>
        public const string TimeoutShellTemplate = "/api/shell/{id}/timeout";
        /// <summary>
        /// Builds the &apos;/api/shell/{id}/timeout&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string TimeoutShell(string id, ShellTimeoutRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            var path = "/api/shell/" + RouteValuePolicy.Escape(id, nameof(id)) + "/timeout";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Skills&apos; routes.
    /// </summary>
    public static class Skills
    {
        /// <summary>
        /// The &apos;GET /api/skill&apos; route template.
        /// </summary>
        public const string ListSkillsTemplate = "/api/skill";
        /// <summary>
        /// Builds the &apos;/api/skill&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListSkills(SkillListRequest? request = null)
        {
            var path = "/api/skill";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Vcs&apos; routes.
    /// </summary>
    public static class Vcs
    {
        /// <summary>
        /// The &apos;GET /api/vcs&apos; route template.
        /// </summary>
        public const string GetVcsTemplate = "/api/vcs";
        /// <summary>
        /// Builds the &apos;/api/vcs&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetVcs(VcsRequest? request = null)
        {
            var path = "/api/vcs";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }

    /// <summary>
    /// Defines the &apos;Websearch&apos; routes.
    /// </summary>
    public static class Websearch
    {
        /// <summary>
        /// The &apos;GET /api/websearch/provider&apos; route template.
        /// </summary>
        public const string GetProvidersTemplate = "/api/websearch/provider";
        /// <summary>
        /// Builds the &apos;/api/websearch/provider&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetProviders(WebsearchProvidersRequest? request = null)
        {
            var path = "/api/websearch/provider";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;POST /api/websearch&apos; route template.
        /// </summary>
        public const string QueryTemplate = "/api/websearch";
        /// <summary>
        /// Builds the &apos;/api/websearch&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string Query(WebsearchQueryPostRequest? request = null)
        {
            var path = "/api/websearch";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }
}
