// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Defines the wire route of every generated operation.
/// </summary>
public static class OpenCodeRoutes
{
    /// <summary>
    /// Defines the &apos;Health&apos; routes.
    /// </summary>
    public static class Health
    {
        /// <summary>
        /// The &apos;GET /api/health&apos; route.
        /// </summary>
        public const string Get = "/api/health";
    }

    /// <summary>
    /// Defines the &apos;Sessions&apos; routes.
    /// </summary>
    public static class Sessions
    {
        /// <summary>
        /// The &apos;POST /api/session&apos; route.
        /// </summary>
        public const string CreateSession = "/api/session";
        /// <summary>
        /// The &apos;GET /api/experimental/session/{sessionID}/log&apos; route template.
        /// </summary>
        public const string GetLogTemplate = "/api/experimental/session/{sessionID}/log";
        /// <summary>
        /// Builds the &apos;/api/experimental/session/{sessionID}/log&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetLog(string sessionId, SessionLogRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            var path = "/api/experimental/session/" + Uri.EscapeDataString(sessionId) + "/log";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddText("after", request.After);
            query.AddBoolean("follow", request.Follow);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/message/{messageID}&apos; route template.
        /// </summary>
        public const string GetMessageTemplate = "/api/session/{sessionID}/message/{messageID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/message/{messageID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "messageId">The &apos;messageID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string GetMessage(string sessionId, string messageId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(messageId);
            if (messageId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(messageId));
            }

            return "/api/session/" + Uri.EscapeDataString(sessionId) + "/message/" + Uri.EscapeDataString(messageId);
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}&apos; route template.
        /// </summary>
        public const string GetSessionTemplate = "/api/session/{sessionID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string GetSession(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + Uri.EscapeDataString(sessionId);
        }

        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/message&apos; route template.
        /// </summary>
        public const string ListMessagesTemplate = "/api/session/{sessionID}/message";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/message&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListMessages(string sessionId, MessageListRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            var path = "/api/session/" + Uri.EscapeDataString(sessionId) + "/message";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddText("limit", request.Limit);
            query.AddOrder("order", request.Order);
            query.AddText("cursor", request.Cursor);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/session&apos; route template.
        /// </summary>
        public const string ListSessionsTemplate = "/api/session";
        /// <summary>
        /// Builds the &apos;/api/session&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListSessions(SessionListRequest? request = null)
        {
            var path = "/api/session";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddText("workspace", request.Workspace);
            query.AddText("limit", request.Limit);
            query.AddOrder("order", request.Order);
            query.AddText("search", request.Search);
            query.AddParentFilter("parentID", request.ParentId);
            query.AddText("directory", request.Directory);
            query.AddText("project", request.Project);
            query.AddText("subpath", request.Subpath);
            query.AddText("cursor", request.Cursor);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/session/{sessionID}&apos; route template.
        /// </summary>
        public const string RemoveSessionTemplate = "/api/session/{sessionID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveSession(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + Uri.EscapeDataString(sessionId);
        }

        /// <summary>
        /// The &apos;POST /api/session/{sessionID}/rename&apos; route template.
        /// </summary>
        public const string RenameSessionTemplate = "/api/session/{sessionID}/rename";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/rename&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string RenameSession(string sessionId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
            if (sessionId is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
            }

            return "/api/session/" + Uri.EscapeDataString(sessionId) + "/rename";
        }
    }

    /// <summary>
    /// Defines the &apos;Shells&apos; routes.
    /// </summary>
    public static class Shells
    {
        /// <summary>
        /// The &apos;POST /api/shell&apos; route template.
        /// </summary>
        public const string CreateShellTemplate = "/api/shell";
        /// <summary>
        /// Builds the &apos;/api/shell&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string CreateShell(ShellCreateRequest? request = null)
        {
            var path = "/api/shell";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/shell/{id}&apos; route template.
        /// </summary>
        public const string GetShellTemplate = "/api/shell/{id}";
        /// <summary>
        /// Builds the &apos;/api/shell/{id}&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string GetShell(string id, ShellRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            var path = "/api/shell/" + Uri.EscapeDataString(id);
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;GET /api/shell&apos; route template.
        /// </summary>
        public const string ListShellsTemplate = "/api/shell";
        /// <summary>
        /// Builds the &apos;/api/shell&apos; route.
        /// </summary>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string ListShells(ShellListRequest? request = null)
        {
            var path = "/api/shell";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;DELETE /api/shell/{id}&apos; route template.
        /// </summary>
        public const string RemoveShellTemplate = "/api/shell/{id}";
        /// <summary>
        /// Builds the &apos;/api/shell/{id}&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string RemoveShell(string id, ShellRemoveRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            var path = "/api/shell/" + Uri.EscapeDataString(id);
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }

        /// <summary>
        /// The &apos;PATCH /api/shell/{id}/timeout&apos; route template.
        /// </summary>
        public const string TimeoutShellTemplate = "/api/shell/{id}/timeout";
        /// <summary>
        /// Builds the &apos;/api/shell/{id}/timeout&apos; route.
        /// </summary>
        /// <param name = "id">The &apos;id&apos; route value.</param>
        /// <param name = "request">The request shaping the query.</param>
        /// <returns>The escaped route.</returns>
        public static string TimeoutShell(string id, ShellTimeoutRequest? request = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (id is "." or "..")
            {
                throw new ArgumentException("Route values must not be dot segments.", nameof(id));
            }

            var path = "/api/shell/" + Uri.EscapeDataString(id) + "/timeout";
            if (request is null)
            {
                return path;
            }

            var query = new QueryStringBuilder();
            query.AddLocation("location", request.Location);
            return path + query.Value;
        }
    }
}
