// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Defines the wire route of every generated operation.
/// </summary>
public static class OpenCodeRoutes
{
    /// <summary>
    /// Defines the &apos;Health&apos; routes.
    /// </summary>
    public static class Health
    {
        /// <summary>
        /// The &apos;GET /api/health&apos; route.
        /// </summary>
        public const string Get = "/api/health";
    }

    /// <summary>
    /// Defines the &apos;Sessions&apos; routes.
    /// </summary>
    public static class Sessions
    {
        /// <summary>
        /// The &apos;GET /api/session/{sessionID}/message/{messageID}&apos; route template.
        /// </summary>
        public const string GetMessageTemplate = "/api/session/{sessionID}/message/{messageID}";
        /// <summary>
        /// Builds the &apos;/api/session/{sessionID}/message/{messageID}&apos; route.
        /// </summary>
        /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
        /// <param name = "messageId">The &apos;messageID&apos; route value.</param>
        /// <returns>The escaped route.</returns>
        public static string GetMessage(string sessionId, string messageId)
        {
            ArgumentException.ThrowIfNullOrEmpty(sessionId);
            ArgumentException.ThrowIfNullOrEmpty(messageId);
            return "/api/session/" + Uri.EscapeDataString(sessionId) + "/message/" + Uri.EscapeDataString(messageId);
        }
    }
}
