// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The opencode API client and composition root.
/// </summary>
public class OpenCodeClient : IDisposable
{
    private readonly Pipeline? _pipeline;
    private readonly SessionsClient? _sessions;
    /// <summary>
    /// Initializes a client that owns its connection to the endpoint.
    /// </summary>
    /// <param name = "options">The client options; the endpoint is required.</param>
    public OpenCodeClient(OpenCodeClientOptions options)
    {
        _pipeline = Pipeline.Create(options);
        _sessions = new SessionsClient(_pipeline);
    }

    /// <summary>
    /// Initializes a client over an injected transport the client never disposes; friend-assembly test surface.
    /// </summary>
    /// <param name = "httpClient">The injected HTTP client.</param>
    /// <param name = "options">The client options; the endpoint is required.</param>
    internal OpenCodeClient(HttpClient httpClient, OpenCodeClientOptions options)
    {
        _pipeline = Pipeline.Create(httpClient, options);
        _sessions = new SessionsClient(_pipeline);
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected OpenCodeClient()
    {
    }

    /// <summary>
    /// Releases the owned transport resources.
    /// </summary>
    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Releases the owned transport resources.
    /// </summary>
    /// <param name = "disposing">Whether managed state should be released.</param>
    protected virtual void Dispose(bool disposing)
    {
        if (disposing)
        {
            _pipeline?.Dispose();
        }
    }

    /// <summary>
    /// Gets the &apos;Sessions&apos; collection client.
    /// </summary>
    public virtual SessionsClient Sessions => _sessions ?? throw MockSeam.CreateError("OpenCodeClient", "Sessions");
    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("OpenCodeClient", "Pipeline");

    /// <summary>
    /// Check server health
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;HealthResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    public virtual Task<HealthResponse> GetHealthAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Health.Get, HealthResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
